### ISSUE TITLE
Improve on transmute for bindgen structs

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#10]
Is there a way to improve upon [this](https://github.com/zenithdb/zenith/blob/4b559435383c39bcc495b00e6e3df2509dbc6ca9/postgres_ffi/src/lib.rs#L19)?

```rust
    // Initialize an all-zeros ControlFileData struct
    pub fn new() -> ControlFileData {
        let controlfile: ControlFileData;

        let b = [0u8; SIZEOF_CONTROLDATA];
        controlfile = unsafe {
            std::mem::transmute::<[u8; SIZEOF_CONTROLDATA], ControlFileData>(b)
        };

        return controlfile;
    }
}
```

Ideally we could have some automatically derived functions that convert to/from `[u8]`.

**Comment by ericseppanen** [comment]
The `CheckPoint` and `ControlFileData` structs contain `bool` members, and could be used to trigger undefined behavior if we use `transmute`.

:(

**Comment by lubennikovaav** [comment]
Any ideas on how to do it correctly?
We can always serialize it manually, using get_u32_le() functions, as I did in the first version. The only problem I see with this approach is the need to write and support extra code.

**Comment by ericseppanen** [comment]
I forgot that I had filed this. I think this conversation has moved to issue #6.
