### ISSUE TITLE
WalProposerRecovery should check that all necessary WAL is provided by Safekeeper

### ISSUE THREAD

**Issue by yeputons** [zenithdb/zenith#1014]
See the initial comment by @arssher here: https://github.com/zenithdb/zenith/pull/777#issuecomment-956151476

> ..., there is a small bug in WalProposerRecovery: proposer should check that he is provided with enough wal till its epochStartLsn, not bail out on some error earlier. ...
> There is also a small risk of overproviding wal proposer with too much WAL in the presence of concurrent compute, but 1) this can be checked on proposer side as well 2) it is eventually harmless as terms will settle the situation, though better to notice this early.

**Comment by petuhovskiy** [comment]
This task was confused with https://github.com/zenithdb/zenith/issues/861, and this issue was fixed by https://github.com/zenithdb/postgres/pull/147.
