### ISSUE TITLE
implement a better memory state management of the downloads/uploads/other sync states:

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1049]
without this pageserver may report the LSNs that are preserved locally as if they are also already in s3, when they are not there yet

- pageserver needs to be able to know more about remote timeline and their sync states (currently it's accessible in the sync loop only)
- sync states need to be better synchronized [details](https://github.com/zenithdb/zenith/pull/874#discussion_r764097220)

In addition to that, the state contents (`disck_consistent_lsn`) has to be available from regular pageserver code. Currently it works incorrect for locally available timelines, returning latest local Lsn instead of the actual remote one.

**Comment by hlinnaka** [comment]
see also https://github.com/zenithdb/zenith/issues/1264

**Comment by stepashka** [comment]
also relates to #997

**Comment by LizardWizzard** [comment]
Fixed by #1163
