### ISSUE TITLE
Long pageserver shutdown time

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#1056]
This ticket is motivated by my experiments with large data:
https://github.com/zenithdb/zenith/issues/906#issuecomment-1000737375
Shutdown of the server takes about one hour!
And it is with checkpoint_interval=1s and checkpoint_distance=256Mb.
So in theory there should be not more than 256Mb of unflushed data.
And 1 hour is definitely too much for flushing 256Mb,

I tried to reproduce the problem with smaller data set at my notebook.
I just do pgbench -i -s 1000. And results were disappointing.
With  `max_replication_flush_lag=1GB, max_replication_apply_lag=10GB`
compute crashed with core dump. Back pressure caused termination of wal sender due to timeout expiration
and then recursive abort of transaction (abort called inside abort) cause panic of postgres.

With default back pressure values `max_replication_flush_lag=160MB, max_replication_apply_lag=1500MB`
initialization is successfully completed. But it was painful to watch this process:
checkpoint iteration takes 1-2 minutes and upload process is interrupted by such minute pauses. ~10 seconds of work followed by ~30 seconds pause.

As a result initialization takes so much time:
```
done in 1964.66 s (drop tables 0.00 s, create tables 0.02 s, client-side generate 632.13 s, vacuum 553.34 s, primary keys 779.17 s).
```

Then after end of initialization and without workload, checkpointer is catched up and checkpoint iteration completed in fraction of second. Then I want to stop pageserver and ... have to wait more than one minute until final checkpoint is completed. Certainly one minute is not one hour. But size of pgbench database with scale 1000 is just 16Gb (100 times smaller than at EC2). And one minute is still too long for flushing 256Mb.

It seems to me that the main problem is that now in layered repo checkpoint combines page reconstruction and flushing data to the disk.

**Comment by knizhnik** [comment]
Looks like such simple patch fixes the problem:

Before:
time ./target/release/zenith stop
real	0m47,087s

After:
time ./target/release/zenith stop
real	0m2,008s

Is there is something wrong with non creating image layers on shutdown?

**Comment by hlinnaka** [comment]
https://github.com/zenithdb/zenith/pull/1057 was pushed, this can be closed now @knizhnik ?
