### ISSUE TITLE
Where can I found the SQL Parser?

### ISSUE THREAD

**Issue by BowenXiao1999** [zenithdb/zenith#1064]
Hi all! Thanks for the great effort for public this repo.

I am trying to learn the code and found it hard to locate the parser code/AST deifinition. Which files/part/code path should I look up? 

Thanks!

**Comment by kelvich** [comment]
Hi! Zenith is a storage layer for postgres, so query parsing and execution is done by postgres. You can look at the parser here https://github.com/zenithdb/postgres/blob/main/src/backend/parser/gram.y or here https://github.com/postgres/postgres/blob/master/src/backend/parser/gram.y
