### ISSUE TITLE
log timeline id in compute logs

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1067]
safekeeper & pageserver both log timeline id in their logs
in order to make it easier to investigate issues with the timelines, let's log the timeline id in in compute logs too

possibly relevant, but doesn't seem to help in our case:
https://www.postgresql.org/docs/14/runtime-config-logging.html

implementation idea:
add timeline id log collection pipeline?

**Comment by stepashka** [comment]
@cicdteam , WDYT?

**Comment by cicdteam** [comment]
if it help solve problems then why not.

**Comment by stepashka** [comment]
there's still no timeline id in the compute logs

**Comment by cicdteam** [comment]
@stepashka 
now compute logs labeled by some `zenit_` labels, one of is `zenith_timeline` so we can filter logs by timeline id. I think you can close this issue.
