### ISSUE TITLE
Failing test: test_pageserver_catchup_while_compute_down

### ISSUE THREAD

**Issue by bojanserafimov** [zenithdb/zenith#1072]
https://app.circleci.com/pipelines/github/zenithdb/zenith/3877/workflows/3a9bb165-5b51-4d33-84f7-c5b266f5af8e/jobs/34213/tests

It failed on a refactor-only change on my branch so I'm sure it will fail on main eventually. Seems like a serious bug since it loses data.

**Comment by LizardWizzard** [comment]
Failed for my PR too: https://app.circleci.com/pipelines/github/zenithdb/zenith/3886/workflows/0c464e8a-9fc1-48a0-91eb-c66ff48858e0/jobs/34337

I've run the test locally for 10 times and there was no errors

**Comment by bojanserafimov** [comment]
Could be explained by https://github.com/zenithdb/zenith/issues/1074

In this test we stop all safekeepeers while pageserver is down. In the issue above you'll see that safekeepers currently don't wait for pageserver to write an s3 snapshot before they go down, so data gets lost there.

**Comment by bojanserafimov** [comment]
@anna should this be included in the limited preview milestone? I think there's one more flaky test as well.

**Comment by hlinnaka** [comment]
We haven't seen this for a while. It's probably been "accidentally" fixed. Closing, but let's reopen if it reappears.
