### ISSUE TITLE
A lot of time is spent in `get_rel_exists()`

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#1077]
Looking at our metrics I noticed that a lot of time is spent in get_rel_exists:
```
pageserver_smgr_query_time_sum{smgr_query_type="get_page_at_lsn"} 9157.3797849
pageserver_smgr_query_time_count{smgr_query_type="get_page_at_lsn"} 7600653
pageserver_smgr_query_time_sum{smgr_query_type="get_rel_exists"} 3259.6117061360087
pageserver_smgr_query_time_count{smgr_query_type="get_rel_exists"} 108790
pageserver_smgr_query_time_sum{smgr_query_type="get_rel_size"} 0.000171424
pageserver_smgr_query_time_count{smgr_query_type="get_rel_size"} 43
```
get_rel_exists is sent to pageserver much frequently than get_rel_size, because we have local cache in smgr) for relation size. 
And although their implementation at pageserver is almost the same, 
average time for `get_rel_size` is 4usec and for `get_rel_exists` 32msec. But it seems to me that it is also caused by relsize cache: `get_rel_size` is called at the very beginning where there is no workload, while `get_rel_exists` is called under workload and compete for layers map lock.

So I see two solutions:
1. Use local cache for  get_rel_exists. The challenge is that Postgres is not using smgr for dropping relations: it just unlink files directly. So Zenith smgr doesn't know that relation is dropped. This is why I think current relsize cache can not be used for `get_rel_exists` .
We can extend SMGR API and let zenith receive such notification.  But it requires more changes in Postgres core.
2. Optimize locking of layers. Try to reduce amount of time layer map lock is hold.

**Comment by knizhnik** [comment]
Some more info: `handle_get_rel_exists_request` spent most of the time in `wait_or_get_last_lsn`. smgrexists is used mostly for checking of FSM page.
And it is done during truncate (not only while user's TRUNCATE command, but mostly in truncate performed by vacuum). Truncate also adjust lastWrittenLsn, causing subsequent `smgrexists` to wait for most recent WAL.

So it seems to be safe to use current relsize cache for in `zenith_exists` (because it is used for FSM pages and not to check if relation is dropped or not).
But if my original concern against using relsize cache for zenith_exists is true, then... current approach is also not correct, because it is using `last_evicted_lsn`, rather than `flush_lsn`.

**Comment by hlinnaka** [comment]
This issue is still open because https://github.com/zenithdb/postgres/pull/113 had to be reverted. It wasn't that PRs fault as such, but it exposed issues with backpressure which caused test failures. Once https://github.com/zenithdb/zenith/issues/1242 and https://github.com/zenithdb/zenith/issues/1189 have been pushed, we should try to enable https://github.com/zenithdb/postgres/pull/113 again.

**Comment by stepashka** [comment]
adding  you as one of the assignees here as you've started #1326

**Comment by knizhnik** [comment]
Merged
