### ISSUE TITLE
storage nodes deployment requirement

### ISSUE THREAD

**Issue by lni** [zenithdb/zenith#1078]
Thanks for this very interesting project! Will definitely closely follow in 2022!

Just a quick question, to play with the latest version in main, do I need to have many page server nodes running on different VMs like described in the Aurora paper? I mean according to the 2nd paragraph on the 3rd page of the original paper - 

> Segments are now our unit of independent background noise
> failure and repair. We monitor and automatically repair faults as
> part of our service. A 10GB segment can be repaired in 10
> seconds on a 10Gbps network link   

To enjoy the above mentioned "independent background noise failure and repair", it seems to me that segments should be hosted on a separate VM nodes (probably on different racks by using the spread placement groups policy).  

I understand that I can probably just launch multiple page server nodes on a single VM to have a test drive without worrying about failures & repairs. Just wondering what is the expected deployment requirement when correlated VM failures can't be ignored. 

Thanks!

**Comment by kelvich** [comment]
Thank you for the kind words!

Our durability model is slightly different from the Aurora one and looks more like the [MS Socrates](https://www.microsoft.com/en-us/research/publication/socrates-the-new-sql-server-in-the-cloud/).

Namely, we do separate recent WAL storage (safekeepers) from the page storage (pageservers). Safekeepers use paxos-like consesus to tolerate failures. Pageservers transform that WAL to pages and store most of the data and always stream that data to S3 -- when data is on the S3 up to some lsn pageserver allows safekeepers to delete corresponding WAL. You can find some details here: https://miro.com/app/board/o9J_lw7LFnQ=/

So the main durability invariant is following: data is either stored as an unprocessed WAL on the quorum of safekeepers or it is stored in S3 as files with data pages. So pageserver acts as a cache for quick access to page, but it can be lost and recovered from S3 and safekeepers.
