### ISSUE TITLE
use actual remote consistent lsn instead of local on disk consistent lsn

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#1104]
Currently we do not keep remote consistent lsn in local timelines and use local on disk consistent lsn when we report it back to safekeeper which thinks that it is remote consistent lsn and can decide to truncate wal that is not present in s3 yet

**Comment by SomeoneToIgnore** [comment]
Here's another one on the similar issue: https://github.com/zenithdb/zenith/issues/1049

**Comment by LizardWizzard** [comment]
Yeah, I forgot that we already track that and I didnt find it, thanks!
