### ISSUE TITLE
Introduce node id to identify pageservers (other services)

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#1105]
Sometimes it is desirable to distinguish between different instances of a particular service, connection string may be used for that but it is unstable because one service may have more than one address e.g when accessed from different networks/have multiple domain names associated with it. 

Safekeepers are currently in progress of gaining this feature (#1081) but it is needed for other services too. I believe that It is beneficial to implement it in some unified way somewhere in zenith_utils.

ref #886

**Comment by kelvich** [comment]
+1
