### ISSUE TITLE
Handle thread spawn failures instead of using unwrap

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1107]

**Comment by kelvich** [comment]
One more thought: we should fix that `unwrap()`, but IMO bigger problem here is we allow `page_service` to die without tearing down whole process. Is it possible to intercept unwraps only in the per-tennant threads (to avoid shutting down everything) and do not intercept them in pageserver-wide threads (to shut down, b/c it is better then trying to fly with one wing).

**Comment by hlinnaka** [comment]
The unwraps() have been fixed in https://github.com/zenithdb/zenith/pull/1108.

**Comment by stepashka** [comment]
the parent issue is closed: #1092
does this mean that this is also closed?
please, reopen if not :)
