### ISSUE TITLE
Docker image build time on main is huge

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#1113]
It took 25 minutes to build the docker image. The reason is that it builds everything from scratch without caching

https://app.circleci.com/pipelines/github/zenithdb/zenith/3967/workflows/af369227-1d25-48ad-bd58-57721d042abf/jobs/35386

@cicdteam Is it known issue?

**Comment by cicdteam** [comment]
will look how to optimize it in ci and in Dockerfiles itself

**Comment by SomeoneToIgnore** [comment]
I've taken a stab at it and can share more context.

1. First, there are multiple docker image builds happening nowadays:

* one as e2e tests for https://github.com/zenithdb/console/ repo
* one as e2e tests for https://github.com/zenithdb/zenith repo

While they do build the same image, they do that separately and not sharing either build cache (that is nonexistent) or build results.
We also plan to add arm builds at some point, so those builds could double, if we decide to run e2e tests with arm images too.

2. The image builds and e2e tests are run on GitHub actions only, CircleCI is not involved into that.

3. I don't think we can expect big decrease in rust compilation speed with time. We can sure put some effort into crate minimization, but no drastic compilation decrease in the near future can be expected. On the other hand, we do run the same compilation multiple times in a row, so feels like it's also more profitable get the build caching on board instead.

-------------

Caching can be done two different ways:

* cache via https://github.com/Swatinem/rust-cache and similar using GitHub actions mechanism.
Those tools are useful when builds is happening on the build agent, yet our build agent runs the `docker build ...` command instead, fully encapsulating whatever build side-effects we have.
It's possible to pass fs into `docker build` process with docker buildkit, but I'm not entirely sure that it would work fully with the GitHub Actions caching.
It's possible to rework this and we will have to eventually, if we plan to deliver native platform binaries in some form and/or test the builds on macOs. 

* cache via https://github.com/mozilla/sccache , https://github.com/paritytech/cachepot and similar using a distributed cache

There's a way to configure sccache to use an arbitrary S3 bucket via IAM or direct credentials usage.
Alas, sccache itself is not currently supporting modern S3 protocol, so it does not work with the new buckets (it will get improved with https://github.com/mozilla/sccache/pull/1086)
Yet there's a fork of this tool, https://github.com/paritytech/cachepot that has pretty much the same settings and works nice with modern S3.

To use that, we have to create a bucket in our AWS, then adjust the `zimg` Dockerfiles in https://github.com/zenithdb/docker-images/ with sccache/cachepot installation and a bunch of env vars, smth. like

```
export CACHEPOT_BUCKET="some-sample-bucket"
export AWS_REGION="eu-north-1"
export AWS_ACCESS_KEY_ID="..."
export AWS_SECRET_ACCESS_KEY="..."
export RUSTC_WRAPPER="/usr/local/cargo/bin/cachepot"
```

This way it works for me, yet does not show big impact in arm builds. 
We can try `cachepot` already and see if it brings any gains to our build speed.

**Comment by SomeoneToIgnore** [comment]
In general, I think sccache/cachepot is still a right direction to go in our set up (with builds run in Docker images) and we should debug and make it better.
I've added stats printing as a first step: https://github.com/zenithdb/zenith/pull/1387 that will show multiple things:
* what kind of cache was configured 
* cache misses
* whether cachepot was at all enabled
