### ISSUE TITLE
build dashboard with graphing CI test results between runs

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#1129]
this is about the output of this test: https://app.circleci.com/pipelines/github/zenithdb/zenith/4049/workflows/25af709b-ca88-4c53-9279-4fc2bb5aba70/jobs/36408/steps

implementation ideas:
add a step to push the results somewhere
it's likely that prometheus isn't a best fit for this data, so ztoring in postgres, in zenith is a good idea!

**Comment by LizardWizzard** [comment]
These are already stored in https://zenithdb.github.io/zenith-perf-data/reports/local.html
