### ISSUE TITLE
Metrics doesn't with large number of layers/files

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#1134]
When metrics are obtained on large database I got the following error:
```
ERROR page server thread exited with error err=invalid message length
```

Not so clear how to reproduce and debug it...

**Comment by hlinnaka** [comment]
With commit adb0b3dadaf5a4f099e13adeaf8291c2d4b94550, you should also get a backtrace. Maybe that will help to pinpoint it, if you can reproduce it.

**Comment by knizhnik** [comment]
Sorry, it was my fault: HTTP server was listening different port.
I expected that when I run tests, it is always 15001, but looks like it find first unused and in this case it was 15003
