### ISSUE TITLE
Low local performance with single safekeeper compared to single synchronous replica

### ISSUE THREAD

**Issue by petuhovskiy** [zenithdb/zenith#1141]
I ran pgbench tests from https://github.com/zenithdb/zenith/pull/1121 on [latest zenithdb/postgres](https://github.com/zenithdb/postgres/tree/walsender-logs), results:

walproposer + safekeeper, single linux vm:
- test_walproposer_pgbench.pgbench_init: 106.750 s
- test_walproposer_pgbench.tps_pgbench: 725.7677 
- test_walproposer_pgbench.walmessage_size_begin: 125781 b
- test_walproposer_pgbench.walmessage_size_end: 11767 b
- average CPU usage: ~15% on every core

postgres master + synchronous replica, single linux vm:
- test_vanilla_pgbench.pgbench_init: 139.660 s
- test_vanilla_pgbench.tps_pgbench: 5,699.1125 
- test_vanilla_pgbench.walmessage_size_begin: 130677 b
- test_vanilla_pgbench.walmessage_size_end: 563 b
- average CPU usage: ~75% on every core

When running walproposer, backends are spending a lot of time in "COMMIT waiting for LSN", that should be the reason of low CPU usage and low performance.

**Comment by knizhnik** [comment]
I wonder if metrics are reported correctly: walmessage_size_end: 11767 b  for zenith and walmessage_size_end: 563 b for vanilla?

**Comment by petuhovskiy** [comment]
Metrics are correct, but it seems that I was running debug build locally and TPS are not fully relevant.

Here are results of the same test, but in release:
```
test_walproposer_pgbench.pgbench_init: 106.130 s
test_walproposer_pgbench.tps_pgbench: 1,067.7128 
test_walproposer_pgbench.walmessage_size_begin: 125714 b
test_walproposer_pgbench.walmessage_size_end: 13986 b
test_vanilla_pgbench.pgbench_init: 146.680 s
test_vanilla_pgbench.tps_pgbench: 5,178.6690 
test_vanilla_pgbench.walmessage_size_begin: 130573 b
test_vanilla_pgbench.walmessage_size_end: 497 b
```


Also, here is benchmark job in CI: https://app.circleci.com/pipelines/github/zenithdb/zenith/4081/workflows/a7638859-c007-4f3f-90e0-6b8adacc2535/jobs/36841 
CI results:
```
test_walproposer_pgbench.pgbench_init: 36.130 s
test_walproposer_pgbench.tps_pgbench: 6,498.5651 
test_walproposer_pgbench.walmessage_size_begin: 126071 b
test_walproposer_pgbench.walmessage_size_end: 15606 b
test_vanilla_pgbench.pgbench_init: 40.940 s
test_vanilla_pgbench.tps_pgbench: 3,338.4917 
test_vanilla_pgbench.walmessage_size_begin: 130044 b
test_vanilla_pgbench.walmessage_size_end: 640 b
```

It's very strange that results on my linux cloud vm and in CI are completely different.

Also walmessage_size_end seems to match between all runs, and it's much larger for walproposer.

**Comment by petuhovskiy** [comment]
I enabled [syncrep.c logs](https://github.com/zenithdb/postgres/blob/main/src/backend/replication/syncrep.c#L535) to see stats on releases of waiting backends.

When we receive ack from walreceiver/safekeeper, we have this line in logs. Number of procs up to flush is the exact number of released backends. I compared these stats for safekeeper and walreceiver.
```
released 0 procs up to write 0/A2334AA8, 1 procs up to flush 0/A2334AA8, 0 procs up to apply FFFFFFFF/FFFFFFFF
```

walproposer.c + safekeeper:
```
sort -n flush.log | uniq -c
  21376 0
  32541 1
   4178 2
   1959 3
   1109 4
    536 5
    270 6
     82 7
     28 8
      2 9
      1 14
      1 15
      1 18
      2 21
```

walsender.c + walreceiver.c:
```
sort -n flush.log | uniq -c
  53585 0
    670 1
    691 2
    650 3
    760 4
    914 5
   1061 6
   1258 7
   1544 8
   1643 9
   1762 10
   1801 11
   1796 12
   1548 13
   1428 14
   1217 15
    953 16
    741 17
    561 18
    410 19
    307 20
    163 21
    135 22
     89 23
     50 24
     23 25
     16 26
     13 27
      2 28
      4 29
      6 32
```
So, walreceiver generally releases more backends => they process more transactions => performance is better. 
I'm not exactly sure why this is happening, but it could be differences in between safekeeper and walreceiver. Walreceiver has optimization where it reads and processes CopyData messages in non-blocking mode, and sends ack back / performs flush to disk only when the socket is empty (https://github.com/zenithdb/postgres/blob/main/src/backend/replication/walreceiver.c#L447-L491). We don't do this in safekeeper yet.

Also, this issue is still non-reproducible in CI, but probably exists on other linux vms.

**Comment by petuhovskiy** [comment]
Tried to run tests again, but now with disabled fsync. It looks like fsync and optimizations around it are causing this 4x difference. Without fsync the results are similar everywhere:

| Test info  | pgbench -i -s 200 (time) | pgbench TPS | wal_msg size | pg_wal size |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| **local** walproposer (no checkpoints, fsync=off) | 90 s | 6280 TPS | 816 b | 2720-2592 MB
| **local** vanilla repl (no checkpoints, fsync=off) | 130 s | 6041 TPS | 995 b | 2736-2608 MB
| **CI** walproposer (no checkpoints, fsync=off) | 27 s | 7969 TPS | 442 b | 2752-2592 MB
| **CI** vanilla repl (no checkpoints, fsync=off) | 31 s | 7790 TPS | 584 b | 2768-2608 MB

**Comment by knizhnik** [comment]
I also did some experiments and come to the same conclusion: something is wrong with sync in safekeepers:


pgbench -f update.sql -c 100 -T 100 

| Test info  |  pgbench TPS |
| ------------- | ------------- | 
| vanialla fsync=on | 2818 | 
| vanialla fsync=off | 2750 |
| zenith | 830 |
| zenith nosync=true | 2307 |
| zenith on tmpfs  | 2345 |
| zenith w/o safekeeper | 2600 |


It is not mistyping: vanilla shows better result with fsync=on!!!
And it is similar with zenith with disabled fsyncs in safekeeper which seems to be the main bottleneck.

**Comment by knizhnik** [comment]
Vanilla use one fsync for 10 transactions:
```
number of transactions actually processed: 274087
tps = 2753.263153 (without initial connection time)
knizhnik@xps:~/zenith.main$ fgrep fsync ~/db/logfile.master | wc -l
28244
knizhnik@xps:~/zenith.main$ fgrep XLogFlush ~/db/logfile.master | wc -l
276407
```
I wonder why zenith walproposer is sending in average ~1 transaction.

**Comment by knizhnik** [comment]
With patch my test shows 2188 TPS and average write size 2241.
So twice larger size - twice higher performance.
And it is quite close to nosync results.
But still we are performing sync for less than three transactions while vanilla - 10.

**Comment by arssher** [comment]
On my laptop, with patch combining fsyncs (`sk-try-improve-perf` branch) pgbench -N tps is roughly the same:
```
test_walproposer_pgbench.wal_init_size: 2,592 MB
test_walproposer_pgbench.tps_pgbench: 4,713.8266 
test_walproposer_pgbench.walmessage_size_begin: 125566 b
test_walproposer_pgbench.walmessage_size_end: 623 b
test_walproposer_pgbench.wal_size: 2,688 MB
test_vanilla_pgbench.pgbench_init: 68.880 s
test_vanilla_pgbench.wal_init_size: 2,608 MB
test_vanilla_pgbench.tps_pgbench: 4,574.2987 
test_vanilla_pgbench.walmessage_size_begin: 125650 b
test_vanilla_pgbench.walmessage_size_end: 996 b
test_vanilla_pgbench.wal_size: 2,720 MB
```

walmessage size is smaller in case of walproposer, but data is glued before fsync, so we need new metric for that.

**Comment by knizhnik** [comment]
Vanialla with synchronous replica show 2400 TPS.
Ratio of  fsyncs per commit performed by replica (walreceiver) is even larger: 13
So for some reasons postgres wal receiver is grouping transaction much efficiently than our safekeeper even with patch.

**Comment by knizhnik** [comment]
We need to add metrics which shows number of fsync performed by safekeeper, because currently it doesn't take in account optimization performed by #1266 
I have inserted trace and find out that with this patch number of performed fsyncs per commit is 6. Still 2 times slower than of sync replica.

**Comment by knizhnik** [comment]
Added metric `flush_wal_seconds` for safekeeper. Either I have made some mistake in counting, either today for some reasons zenith working much better, but according to this metrics grouping of commits by #1266 patch
works pretty well: one fsync for 19 commits in average. And achieved TPS is 3117! Faster than vanilla!
But looks like it is just "fluke" - in another run there are 16 commits per fsync and 2600 TPS.

**Comment by petuhovskiy** [comment]
I wrote in https://github.com/zenithdb/zenith/pull/1318#issuecomment-1050836557 that performance of local test is now comparable with vanilla replication, the main issue was using fsync instead of fdatasync, that made a difference of my machine. This issue looks resolved, closing it.
