### ISSUE TITLE
Storage coordination

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#1180]
Implementation part of https://github.com/zenithdb/rfcs/pull/16

Could be done in following steps:
- [ ] choose etcd client library and check that put/get/subscribe work as expected
- [ ] implement safekeeper2safekeeper communications -- that will unblock WAL trimming and S3 pushdown
- [ ] implement pageserver part and drop callmemaybe

last two can be somewhat parallelized

**Comment by stepashka** [comment]
this is closed in favor of zenithdb/zenith#543
