### ISSUE TITLE
Bad backpressure settings

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#1189]
@knizhnik mentioned that sometimes you can get a deadlock with the current backpressure settings. Investigate.

Does the current write/flush/apply defaults make sense?

**Comment by lubennikovaav** [comment]
PR with backpressure defaults change was merged.
It may need some better tuning for specific tests and environments, though.

apply lag is not enabled - now it doesn't make much sense since remote storage is not fully working
