### ISSUE TITLE
Infinite loop doesn't respect Ctrl-C

### ISSUE THREAD

**Issue by nikitashamgunov** [zenithdb/zenith#1196]
snowy-sunset-088328=> 
do $$
begin                                                                  
  for i in 1..100 loop                                                                                      
     insert into nikita select * from nikita;                                                              
  end loop;                                                                                             
end;                                                                                                    
$$;

^Cancel request sent

**Comment by stepashka** [comment]
could be related to #623

**Comment by stepashka** [comment]
cannot reproduce
