### ISSUE TITLE
Bad query planner defaults for single core clients

### ISSUE THREAD

**Issue by antons-antons** [zenithdb/zenith#1212]
select count(*) from <12Gb table>; results in a parallel table scan on the limited preview hardware.
we should not issue parallel plans when we only offer a single core

**Comment by cicdteam** [comment]
@antons-antons just... currently `compute` not limited how many CPU cores to use. Is it problem to run parallel scan if `compute` could utilize 1 core only ?

**Comment by antons-antons** [comment]
yeah, this issue doesn't make sense if we're running on a multiple cores.

**Comment by kelvich** [comment]
> we should not issue parallel plans when we only offer a single core

we don't have a prefetch now and parallel workers may soften that situation a bit -- since few getpage requests can be sent concurrently. However proper testing is needed.
