### ISSUE TITLE
workspace_hack can hide errors where a crate requests wrong feature set

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#123]
[Here](https://github.com/zenithdb/zenith/pull/121/files#r629628946) we found that the `zenith_utils` crate would build from the workspace root, but could not build on its own. This was caused by a missing `features = ["derive"]` for `serde`.

It was a quirk that zenith_utils didn't already depend on `workspace_hack`. (I figured `zenith_utils` was too small to matter, which is probably wrong.) But even if it had depended on `workspace_hack`, we should still ask for all the features we need: in the future, the other crates might no longer use them, leaving us unable to build. `workspace_hack` may hold us afloat for a little while, but things will eventually fail when we update `workspace_hack`.

This is something I've seen a few times now: a crates can get its requested features wrong, and have that problem hidden by something else requesting that feature for us. So far I haven't found any tools to help detect this.

**Comment by ericseppanen** [comment]
I pushed e5df42feefd to add `workspace_hack` as a dependency of `zenith_utils`. This will at least fix the trapdoor that @patins stepped on :)

**Comment by hlinnaka** [comment]
Is there something left to do here, or can we close this?

**Comment by ericseppanen** [comment]
I was hoping that I'd find some better advice/tools for handling workspace dependencies gracefully. [Hakari](https://github.com/facebookincubator/cargo-guppy/tree/main/tools/hakari) seems sort of hack-ish (and doesn't seem to be receiving new commits, so maybe it's abandoned?) and I haven't seen much movement in Cargo itself.

I don't think there's anything we can do in the short term, so it's probably best to close this.
