### ISSUE TITLE
Console displays records incorrectly

### ISSUE THREAD

**Issue by nikitashamgunov** [zenithdb/zenith#1230]
drop table if exists nikita;

create table nikita(id int, a text);

insert into nikita values(1, repeat('a', 4000));

insert into nikita values(1, repeat('a', 40000));

select * from nikita;
![image](https://user-images.githubusercontent.com/758379/152697847-f6a9ff4f-19d2-48e1-ad6e-1951535c277d.png)

**Comment by nikitashamgunov** [comment]
Just realized it's due to formatting. One string is longer and we are aligning strings to the right. I think we should be aligning strings to the left.

**Comment by seymourisdead** [comment]
fixed aligning for query result tables
