### ISSUE TITLE
Collect resource usage per tenant

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#1234]
We collect various prometheus metrics from pageserver and safekeepers, like I/O, CPU usage, disk usage, network bandwidth etc. Let's expose them on a per-tenant basis. That will make it easier to decide which tenant to move if a pageserver is overloaded (rebalancing), or to investigate other issues.

See also https://github.com/zenithdb/zenith/issues/1219

**Comment by dhammika** [comment]
Looks like cpu/mem metrics are from rusage but io stats are already partitioned by tenant_id, 
```
# HELP pageserver_io_size Amount of bytes
# TYPE pageserver_io_size gauge
pageserver_io_size{operation="read",tenant_id="03c487af17ed32a4601e2c80340295a5",timeline_id="1f2a5658d7ba6c75839ed3636e558177"} 3363369
pageserver_io_size{operation="write",tenant_id="03c487af17ed32a4601e2c80340295a5",timeline_id="1f2a5658d7ba6c75839ed3636e558177"} 1024
```
Also noticed composite tags in safekeeper,  
```
# HELP safekeeper_persist_control_file_seconds Seconds to persist and sync control file, grouped by timeline
# TYPE safekeeper_persist_control_file_seconds histogram
safekeeper_persist_control_file_seconds_bucket{timeline_id="03c487af17ed32a4601e2c80340295a5-1f2a5658d7ba6c75839ed3636e558177",le="0.00005"} 0
safekeeper_persist_control_file_seconds_bucket{timeline_id="03c487af17ed32a4601e2c80340295a5-1f2a5658d7ba6c75839ed3636e558177",le="0.0001"} 0
```

**Comment by dhammika** [comment]
New per tenant graphs, 
- Pageserver 
   - [Storage time](https://observer.zenith.tech/goto/I3w7tgP7k?orgId=1)
   - [SMGR query time](https://observer.zenith.tech/goto/GTZItRPnz?orgId=1) 
- Safekeeper 
   - [WAL write bytes](https://observer.zenith.tech/goto/uG6dpRP7z?orgId=1)
   - [WAL write secs](https://observer.zenith.tech/goto/GyLctgE7z?orgId=1)
   - [Control file secs](https://observer.zenith.tech/goto/UzNopgPnk?orgId=1)
   - [Commit LSN](https://observer.zenith.tech/goto/ORUtpRE7z?orgId=1)
   - [Flush LSN](https://observer.zenith.tech/goto/IJx2pRPnz?orgId=1)
