### ISSUE TITLE
Tenant directory exists on disk but not in memory

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#1264]
From pageserver logs in production:

```
2022-02-10T21:24:05.598868Z ERROR Error processing HTTP request: InternalServerError(repo for eed718477b5682aa91f21c41d3a86bb1 already exists
2022-02-10T21:24:05.599459Z ERROR Error processing HTTP request: InternalServerError(Tenant not found for tenant eed718477b5682aa91f21c41d3a86bb1
```
This repeats over and over again.

I think the pageserver somehow got into a state where the tenant directory exists on disk, but the in-memory data structure for it doesn't exist. Maybe the same tenant was created or attached twice concurrently? Or it was detached but it failed in the middle?

Investigate, and make the system more robust so that the on-disk and in-memory state cannot go out of sync.

**Comment by LizardWizzard** [comment]
Attach and detach were not used in production because s3 integration was disabled. Timeline memory state management was significantly reworked in #1163. So I think we can close it and reopen in case we manage to reproduce it. Thoughts @hlinnaka?

**Comment by hlinnaka** [comment]
Ok, closed.
