### ISSUE TITLE
pageserver - doubly nested .zenith directories

### ISSUE THREAD

**Issue by patins** [zenithdb/zenith#127]
The pageserver creates a nested .zenith directory. This happens because the pageserver is daemonized inside the root .zenith directory, and then `zenith_repo_dir` returns `.zenith` as the directory path.

```
pat@delta zenith % ls -la .zenith
...
drwxr-x---   4 pat  staff   128 May 11 15:01 .zenith
...
pat@delta zenith % ls -la .zenith/.zenith
total 0
...
drwxr-x---   9 pat  staff  288 May 11 15:00 1f55566f9f6bc0ae9ddf3082aff4393a
drwxr-x---   9 pat  staff  288 May 11 15:01 f1fd2b85b1c56d4a85a0746100eaef02
```

**Comment by hlinnaka** [comment]
I just bumped into this again while trying to create unit tests. I'll pick this up.
