### ISSUE TITLE
Proper return codes for 'already exists' errors in pageserver http api

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#1294]
Pageserver should return http 409 instead of 500 when branch/tenant already exists.

Right now to properly retry operations console lists all tenants on 500 error to check whether it is already there -- that is extremely hacky.

**Comment by SomeoneToIgnore** [comment]
Have fixed it with https://github.com/zenithdb/zenith/pull/1286/commits/36cdc359972a2aab43599e4ba5c0d5887c1e5d6c , returning 200 for already existing tenant repos.
The corresponding console code for tenant creation gets simplified to regular go code: 
https://github.com/zenithdb/console/pull/782/files#diff-dd7a078cc6918961ff0b46a9d656d355406a51b8acd91cff2018dcf4253a04b5R37-R39

Now tenant creation does not generate a timeline, you have to create the timeline separately (https://github.com/zenithdb/zenith/pull/1286/commits/556a1a9f2684bc48dde4096c452c6a0515ed069c), so already existing tenant directory isn't an obstacle to eagerly return 200, without creating anything.

Let me know, if that's not the right approach and something non-200 have to be returned.

**Comment by SomeoneToIgnore** [comment]
Closed with https://github.com/zenithdb/console/pull/782 and https://github.com/zenithdb/zenith/pull/1286
