### ISSUE TITLE
`zenith push` prototype

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#130]
RFC: [https://github.com/zenithdb/rfcs/blob/push-pull/push-pull.md](push-pull.md)

For starters let's implement push without any auth; only to non-existent branch; move only relation data (one that currently in rocksdb) and skip any non-rel data (one that is stored in snapshots directory).

**Comment by patins** [comment]
Future work includes
- [ ] implementing push with ancestor branches
- [ ] pushing on top of branches that haven't been updates since the last pull/push
- [ ] push by branch name
- [ ] more testing

**Comment by kelvich** [comment]
Decided not to proceed with this approach
