### ISSUE TITLE
Pick a Minimum Supported Rust Version

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#138]
Most Rust projects choose a MSRV and enforce it by doing builds on that version in CI.

Let's pick one or agree that we're all going to upgrade every time a new stable release comes along. Otherwise, we'll hit regular breakages (i.e. #137).

We probably want the following CI builds:
- `cargo check` with MSRV in debug mode
- `cargo build` with latest stable in debug mode
- `cargo build` with latest stable in release mode

I don't think I see a reason to build on nightly in CI right now.

**Comment by ericseppanen** [comment]
For what it's worth, I really like some of the features that have arrived in recent versions:
- Rust 1.51 added const generics, `array::IntoIter`, and a new cargo feature resolver
- Rust 1.50 added `Ord::clamp` and `slice::fill`

**Comment by ericseppanen** [comment]
At some point I added to the README:
> Rust 1.48 or later is also required.

So I guess for now 1.48 is it? I still intend to add a test that runs 'cargo check' on 1.48, so I'll leave this open to track that.

**Comment by hlinnaka** [comment]
Since commit 82725725f, the README says
> [Rust] 1.52 or later is also required.

So that's it for now.
