### ISSUE TITLE
Update build instructions to include dependencies

### ISSUE THREAD

**Issue by spullara** [zenithdb/zenith#183]
To build on Ubuntu I needed to install:

`sudo apt install libreadline-dev bison flex zlib1g-dev libxml2-dev libssl-dev clang`

Along with rust.

**Comment by ericseppanen** [comment]
The full set of dependencies in the CI builds is:
```
build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libcurl4-openssl-dev libssl-dev clang
```
