### ISSUE TITLE
Maintaning of FSM

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#190]
We are not updating FSM fork now, assuming this is just a hint and Postgres can correctly work without it.
It is not completely true: visibility tests are sometimes failed because FSM was not truncated.

This problem was fixed in commits: 2beeb66, ca6ff19, 2291441 in page_server_nonrel_wal_redo.
Fix consists of two parts:
1. Make it possible to access truncated pages. So get_page_at_lsn will return empty page in this instead of throwing error.
2. Handle SMGR_TRUNCATE_VM and SMGR_TRUNCATE_FSM flags of XLOG_SMGR_TRUNCATE WAL record. But only if relation is completely truncated (blkno == 0). If just tail of relation is truncated, then we should map heap block number to correspondent fork block number (which is non-trivial for FSM which is stored as binary tree) and tail bits in last block. Support of arbitrary truncation will require porting to Rust yet another porting of C code from Postgres.

Before starting implementation of partial truncation of VM/FSM, I want to understand whether we need to handle at page server all updates of FSM /VM (not inly truncation)?  Or may be some other approach can be proposed.

**Comment by hlinnaka** [comment]
This is more about the VM than the FSM, I think? The FSM doesn't need to be accurate for correctness, but the VM must not have any bits set incorrectly (clearing bits is always OK though).

**Comment by knizhnik** [comment]
No, in this case it is actually related with FSM. I have not perform deep investigation, but my hypothesis is that presence of FSM allows to allocate new page without extending relation. So in WAL log I do not see any other operations with this relation between truncation and access to the page.

**Comment by hlinnaka** [comment]
Fixed by commit ac60b68d5070b8f1c5533cb076affe3a7c43f2e6.
