### ISSUE TITLE
Predicate lock failure

### ISSUE THREAD

**Issue by knizhnik** [zenithdb/zenith#192]
Sometime (very rarely) index-only-scan isolation test failed because of lack of expected non-serilziable access error:

```
diff -U3 /home/circleci/project/vendor/postgres/src/test/isolation/expected/index-only-scan.out /tmp/test_output/test_isolation/regress/results/index-only-scan.out
--- /home/circleci/project/vendor/postgres/src/test/isolation/expected/index-only-scan.out	2021-05-26 16:14:32.164081499 +0000
+++ /tmp/test_output/test_isolation/regress/results/index-only-scan.out	2021-05-26 16:16:18.740821672 +0000
@@ -18,7 +18,6 @@
 step rywx2: DELETE FROM tabx WHERE id = (SELECT min(id) FROM taby);
 step c2: COMMIT;
 step c1: COMMIT;
-ERROR:  could not serialize access due to read/write dependencies among transactions
 
 starting permutation: rywx2 rxwy1 c1 c2
 step rywx2: DELETE FROM tabx WHERE id = (SELECT min(id) FROM taby);
```

It happens only at circleci and I failed to reproduce it locally.
I do not have any reasonable hypothesis  since predicate locking is not updating tuples and page headers.
It is just maintaining hash and SLRU.

**Comment by hlinnaka** [comment]
Hmm, perhaps it's related to updating the visibility map. If the visibility map is not updated correctly, the 'rywx2' step might not see that the minimum row in taby was being deleted concurrently.

**Comment by knizhnik** [comment]
It was my first guess. But nope:(
I slightly change your DEBUG_COMPARE_LOCAL code to compare visibility map fork also.
It actually doesn't matched.But I have not checked why. Then I just change zenith_read to use local image of visibility map page but it doesn't help: the bug is still reproduced. Also DEBUG_COMPARE_LOCAL checks shows that pages of main fork are identical.

**Comment by knizhnik** [comment]
Actually I found a way to more or less reliably reproduce this problem locally: just need to repeat index-only-scan test many times (repeat "test: index-only-scan" line 100 times in isolation_schedule). Please notice that the problem is not reproduced if test_runner/batch_pg_regress/test_isolation.py is called 100 times with single  "test: index-only-scan" line in isolation_schedule. So lookes like the problem is somehow related with vacuum or om other postgres background activity.

**Comment by knizhnik** [comment]
So the source of the problem is that VACUUM FREEZE put in the WAL XLOG_HEAP2_FREEZE_PAGE record which redo handler (heap_xlog_freeze_page) doesn't  set  PD_ALL_VISIBLE flag. So inserting this WAL record set WAL_LOGGED bit, so image if the page is not forced to be stored in WAL. But as a result we loose PD_ALL_VISIBLE flag.
The following patch fixes the problem, but I am not sure hat it is always correct:

```
diff --git a/src/backend/access/heap/heapam.c b/src/backend/access/heap/heapam.c
index f72ba02894..7e057fe8cc 100644
--- a/src/backend/access/heap/heapam.c
+++ b/src/backend/access/heap/heapam.c
@@ -8616,6 +8616,22 @@ heap_xlog_visible(XLogReaderState *record)
                UnlockReleaseBuffer(vmbuffer);
 }
 
+static int
+heap_count_tuples(Page page)
+{
+       int maxoff = PageGetMaxOffsetNumber(page);
+       int n_tuples = 0;
+
+       for (int offnum = FirstOffsetNumber;
+                offnum <= maxoff;
+                offnum = OffsetNumberNext(offnum))
+       {
+               ItemId itemid = PageGetItemId(page, offnum);
+               n_tuples += ItemIdIsUsed(itemid);
+       }
+       return n_tuples;
+}
+
 /*
  * Replay XLOG_HEAP2_FREEZE_PAGE records
  */
@@ -8664,6 +8680,10 @@ heap_xlog_freeze_page(XLogReaderState *record)
                        heap_execute_freeze_tuple(tuple, xlrec_tp);
                }
 
+               /* ZENITH: set ALL_VISIBLE bit if all tuples on the page are frozen */
+               if (xlrec->ntuples == heap_count_tuples(page))
+                       PageSetAllVisible(page);
+
                PageSetLSN(page, lsn);
                MarkBufferDirty(buffer);
        }
```

**Comment by hlinnaka** [comment]
> So the source of the problem is that VACUUM FREEZE put in the WAL XLOG_HEAP2_FREEZE_PAGE record which redo handler (heap_xlog_freeze_page) doesn't set PD_ALL_VISIBLE flag. So inserting this WAL record set WAL_LOGGED bit, so image if the page is not forced to be stored in WAL. But as a result we loose PD_ALL_VISIBLE flag.

A-ha! Do we violate the rule that the visibility map bit can only be set, if PD_ALL_VISIBLE is also set? Can that happen in PostgreSQL too if you crash at the right place?

BTW, I don't have much confidence in the PD_WAL_LOGGED bit in general. Not sure to do about it, but needs some thinking. For starters, I don't think the flag should be stored in the page header itself, it would be more natural to store it in the buffer header, alongside BM_DIRTY flag. I think we're out of bits there, though. Even better would be to explicitly mark all the code that modifies a page without WAL logging it, that we need to be WAL logged. Add a function calls like "start_unlogged_operations()" and "end_unlogged_operations()" in the index build code that needs it, for example.

Would it be possible to add Asserts to catch this kind of bugs in the future?

**Comment by knizhnik** [comment]
> A-ha! Do we violate the rule that the visibility map bit can only be set, if PD_ALL_VISIBLE is also set? Can that happen in PostgreSQL too if you crash at the right place?

I still do not quite understand how it is possible. PageSetAllVisible is always followed by visibilitymap_set which should insert VISIBLE record in WAL. Redo handler of this record should restore PD_ALL_VISIBLE bit on heap page, as well as correspondent bits of visibility bitmap.

If we look at the WAL dump, we can see that FREEZE record preceds VISIBLE record:

```
rmgr: Heap2       len (rec/tot):   2764/  2764, tx:          0, lsn: 0/0404A230, prev 0/0404A1F0, desc: FREEZE_PAGE cutoff xid 607 ntuples 226, blkref #0: rel
 1663/16384/16495 blk 7
rmgr: Heap2       len (rec/tot):     59/    59, tx:          0, lsn: 0/0404AD00, prev 0/0404A230, desc: VISIBLE cutoff xid 606 flags 0x03, blkref #0: rel 1663
/16384/16495 fork vm blk 0, blkref #1: rel 1663/16384/16495 blk 7
```
I will continue investigations tomorrow.

Concerning moving PD_WAL_LOGGED fro page header to buffer (as BM_DIRTY), it sounds like right approach, but I need to check: in some places we writing to the disk directly though smgr, bypassing buffer cache.

**Comment by knizhnik** [comment]
After more investigations I find out the the source of the problem was actually in this fragment visibilitymap_set:
```
				/*
				 * If data checksums are enabled (or wal_log_hints=on), we
				 * need to protect the heap page from being torn.
				 */
				if (XLogHintBitIsNeeded())
				{
					Page		heapPage = BufferGetPage(heapBuf);

					/* caller is expected to set PD_ALL_VISIBLE first */
					Assert(PageIsAllVisible(heapPage));
					PageSetLSN(heapPage, recptr);
				}
```

WAL logging of hit bits was not enabled and so we have not heap updated page LSN.
I wonder if we should always enable wal_log_hints  For Zenith?

**Comment by hlinnaka** [comment]
> After more investigations I find out the the source of the problem was actually in this fragment visibilitymap_set:
> 
> ```
> 				/*
> 				 * If data checksums are enabled (or wal_log_hints=on), we
> 				 * need to protect the heap page from being torn.
> 				 */
> 				if (XLogHintBitIsNeeded())
> 				{
> 					Page		heapPage = BufferGetPage(heapBuf);
> 
> 					/* caller is expected to set PD_ALL_VISIBLE first */
> 					Assert(PageIsAllVisible(heapPage));
> 					PageSetLSN(heapPage, recptr);
> 				}
> ```

Hmm, so the sequence is like this:

1. PD_ALL_VISIBLE is set on the page. It's not WAL-logged, but the buffer is marked dirty.
2. visibilitymap_set() is called, to set the bit in the VM. The heap buffer is registered with the WAL record, and is marked with PD_WAL_LOGGED, but no full page image is included.
3. The heap page is evicted. Because the page still has the old LSN on it, we don't advance the last-written-LSN value.
4. The heap page is read back, using the old LSN. It doesn't have the PD_ALL_VISIBLE flag set.

Hmm, I wonder if we have other similar bugs. The WAL-logging of the visibility map is a special snowflake, and there's been many subtle bugs in it in PostgreSQL over the years...

> WAL logging of hit bits was not enabled and so we have not heap updated page LSN.
> I wonder if we should always enable wal_log_hints For Zenith?

Yeah, let's turn it on. And let's turn on data checksums, too.

**Comment by knizhnik** [comment]
The sequence is the following:
1. PD_ALL_VISIBLE is set on page and in VM bitmap
2. Heap page is swapped out with wrong LSN (pointing to FREEZE WAL record rather than to VISIBILITY wal record)
3. Heap page is loaded without PD_ALL_VISIBLE bit. VM still marking this page as all-visible which violate Postges invariant (if page is marked as all-visible in VM, then it should also has correspondent bit set).
4. Heap page is update. The code which modifies the page updates  VM only of page if PD_ALL_VISIBLE bit is set. But it is not set and so VM is not updated
5. Index only scan is not checking conflicts  for all-visible pages which is checked using VM. As page is marked as all visible in VM, we do not detect serializable conflict.
