### ISSUE TITLE
Pageserver start/init and config

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#224]
Ansible script to init pageserver and systemd unit to run pageserver now looks like that (ops/pageserver/pageserver.yml in console repo):

```
  - name: init pageserver
    shell:
      cmd: |
        sudo -u pageserver {{ansible_env.HOME}}/zenith/target/debug/pageserver --init --workdir /var/db/pageserver
    args:
      chdir: "{{ansible_env.HOME}}/zenith"
      creates: "/var/db/pageserver/timelines"
    environment:
      ZENITH_REPO_DIR: "/var/db/pageserver"
      POSTGRES_DISTRIB_DIR: "{{ansible_env.HOME}}/zenith/tmp_install/"
      PATH: "{{ansible_env.HOME}}/zenith/tmp_install/bin/:{{ ansible_env.PATH }}"
      LD_LIBRARY_PATH: "{{ansible_env.HOME}}/zenith/tmp_install/lib/"
    become: true

  - name: create systemd service
    copy:
      dest: "/etc/systemd/system/pageserver.service"
      content: |
        [Unit]
        Description=Zenith pageserver

        [Service]
        Type=simple
        User=pageserver
        Environment=ZENITH_REPO_DIR=/var/db/pageserver POSTGRES_DISTRIB_DIR={{ansible_env.HOME}}/zenith/tmp_install/ PATH={{ansible_env.HOME}}/zenith/tmp_install/bin/ LD_LIBRARY_PATH={{ansible_env.HOME}}/zenith/tmp_install/lib/
        ExecStart={{ansible_env.HOME}}/zenith/target/debug/pageserver -l 0.0.0.0:6400
        ExecReload=/bin/kill -HUP $MAINPID
        KillMode=mixed
        KillSignal=SIGINT
        TimeoutSec=0

        [Install]
        WantedBy=multi-user.target
```

Some problematic areas:
* PATH and LD_LIBRARY_PATH are not actually needed -- we may set them to POSTGRES_DISTRIB_DIR/bin and POSTGRES_DISTRIB_DIR/lib correspondingly when launching wal-redo postgres.
* mix of env vars and cli keys during init
* necessity to set env variables during usual start

I suggest to change this to following:

1. Init creates necessary data directories and pageserver.toml inside workdir. Workdir is required param. Each config option can be overridden by optional key. Like that:
```
// creates pageserver.toml and necessary subdirs in /my/path. POSTGRES_DISTRIB_DIR 
// would be set to some default value (/usr/local/wal-redo-postgres?) as well as host:port
pageserver init --workdir /my/path 

 // same, but in current directory
pageserver init --workdir .

// override default config values
pageserver init --workdir .  --postgres-distrib /path/to/pg --listen-address 1.2.3.4:1234 
``` 

2. Pageserver run requires only --workdir and read all the stuff from pageserver.toml:
```
pageserver run --workdir /my/path
pageserver run --workdir /my/path --daemonize
```

(opinion or other suggestions are welcomed)

**Comment by kelvich** [comment]
On a second thought, it seems quite weird to require 'run' keyword. Original idea was that we can allow all config-overwriting keys (--postgres-distrib, --listen-address, ...) only for init and keep run keyword clean. However, it is also handy sometimes to force running with some config option set in cli without editing config file. So what about following:
```
// init and set specified keys to config
pageserver --workdir .  --init  --postgres-distrib /path/to/pg --listen-address 1.2.3.4:1234

// run pageserverver and override listen-address (cli key priority higher than config file entry)
pageserver --workdir .  --listen-address 1.2.3.4:1234
```
IMO looks slightly cleaner than previous suggestion. It also would be handy to set workdir to '.' by default.

**Comment by patins** [comment]
Closing with #261
