### ISSUE TITLE
Garbage collect old page versions

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#231]
Design and implement rules for which page versions need to be retained in the page server.

Currently, the Page Server keeps *all* page versions. That obviously doesn't scale, you will run out of disk space eventually. 

```
Timeline, newer LSNs on the right:

------+-----#####-------------+-------+-----++++++++############>
     (4)     (5)             (3)     (3)       (2)      (1)
```
1. Need to keep X amount of recent page versions, for read replicas.

2. To support point-in-time recovery to an arbitrary point, need to
   keep all page versions back to X hours or days. No need to keep
   intermediary states between transaction commits for PITR,
   though. User-visible changes only happen at commits.

3. Need to keep any explicitly tagged points in time ("zenith tag"), aka
   snapshots.

4. When a new timeline is branched, need to keep the page versions at
   the branch point for as long as the new timeline needs them.

5. Admin can request to keep everything in any additional time
   range. Maybe? Do we need this? I think we will have the
   capability anyway, to support (1).

Need to implement UI to specify these things. and the logic to implement these policies in the storage.

**Comment by mklgallegos** [comment]
Hi @hlinnaka 

When you have a chance can you: 

1. assign this issue to someone (I'm doing a general pass through the issues in the v0.1. milestone and noticed this issue did not have an assignee)
2. provide a general update on current status of this issue

**Comment by mklgallegos** [comment]
Hi @hlinnaka this item was put into the done category during the milestone v0.2 planning session on 2021-07-30. I'm closing out. Please re-open if I am mistaken.
