### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#233]
We need to do performance testing before release, and address any serious performance issues that we find.

Deciding what kind of tests to perform is part of the task. pgbench is probably a good start, and maybe TPC-C. Should also measure load and disk space usage, in the page server and WAL safekeeper, to calculate COGS of the cloud service.

-- 

subtasks 
 - [ ] https://github.com/zenithdb/zenith/issues/376

**Comment by gregscds** [comment]
I heard once using pgbench is a pain.

**Comment by hlinnaka** [comment]
> I heard once using pgbench is a pain.

There are some excellent tools at https://github.com/gregs1104/pgbench-tools for that, fortunately ;-).

**Comment by mklgallegos** [comment]
Hi @hlinnaka,

When you have a chance can you: 
1. assign this issue to someone? I'm doing a general pass through the issues in the v0.1. milestone and noticed this issue did not have an assignee
2. provide a general update on current status of this issue?

**Comment by hlinnaka** [comment]
Subtasks: https://github.com/zenithdb/zenith/issues/376 and https://github.com/zenithdb/zenith/issues/376
