### ISSUE TITLE
Write user documentation

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#234]

**Comment by lubennikovaav** [comment]
We will need a chapter that describes things that behave differently from regular postgres.

Ideally, we should provide a smooth migration from postgres to zenith, with no need to change the application and only minor adjustments to config scripts.

Some GUC settings just won't make any sense in zenith, some features will behave differently.
And we need to explain it to users. And to do this we need to figure it out ourselves)
Let's collect open questions here:

- unlogged tables
In PostgreSQL, they don't survive between restarts. 
Will they survive zenith compute node restarts? Should they survive branching? 
The current solution is to simply turn them into permanent tables. Is it good enough?

- checkpoints, bgwriter
Zenith acts as a kind of continuous checkpoint, so we don't need a regular PostgreSQL checkpoint.
How would it impact checkpoint settings? We need to explain it.
Are there any actions in PostgreSQL that are related to checkpoints that we must handle?

- min_wal_size, max_wal_size, wal_keep_size, wal_keep_segments & others
Do any of these settings change their meaning, when we have walkeeper?

**Comment by kelvich** [comment]
cc @mklgallegos

**Comment by mklgallegos** [comment]
10-4 this is on my radar, assigning it to myself

**Comment by stepashka** [comment]
superseded by zenithdb/zenith#891 and zenithdb/zenith#910
