### ISSUE TITLE
cmin/cmax and spec insertion token not WAL logged

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#249]
The values of the cmin/cmax field, and speculative insertion token, are not WAL-logged when a heap tuple is updated. That's OK for Postgres, because those value are only meaningful to the original transaction that updated the tuple, so they're never needed after crash or archive recovery, or in a standby server. But that's a problem for Zenith, because we rely on WAL redo to reconstruct the page even in the primary server. Can we have an option or something in community PostgreSQL to force those to be WAL logged too? Or even WAL-log them unconditionally, they are small after all?

**Comment by mklgallegos** [comment]
@hlinnaka - this item was put in the done category during the milestone v0.2 planning session on 2021-07-30. Please close out and include any relevant comments.
