### ISSUE TITLE
Deal with unlogged tables

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#26]
Currently, the smgr API doesn't differentiate unlogged tables. We will try to read/write them through the page servers, too. Can we detect and force them to be local-only or something?

**Comment by lubennikovaav** [comment]
Note: the test doesn't fail now, because we have a crutch to ignore 'unlogged' keyword and treat all tables as permanent
9f9aa9c300c9bbac296e2c126b3f96701d4e683d
