### ISSUE TITLE
Smgr: cache n_blocks info for relations and avoid spamming pageserver with corresponding requests.

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#27]

**Comment by knizhnik** [comment]
I wonder if we should implement this cache ourselves or use community patch:
https://www.postgresql.org/message-id/flat/CA%2BhUKG%2B7Ok26MHiFWVEiAy2UMgHkrCieycQ1eFdA%3Dt2JTfUgwA%40mail.gmail.com#58e434e54ebe7f46c9bccdc094b51bed

**Comment by lubennikovaav** [comment]
Done in https://github.com/zenithdb/zenith/pull/485
