### ISSUE TITLE
Internal protocol SSL support

### ISSUE THREAD

**Issue by patins** [zenithdb/zenith#282]
My personal focus is pageserver <-> pageserver communications for push.
In the end we should be able to encrypt all of our network communications.

**Comment by ericseppanen** [comment]
We would avoid this issue completely if we stop doing pageserver <-> pageserver communications, and always put the data in s3.

**Comment by mklgallegos** [comment]
> We would avoid this issue completely if we stop doing pageserver <-> pageserver communications, and always put the data in s3.

@ericseppanen - when you refer to always putting the data in s3 are you referring to RFC for "snapshot-first storage" architecture (https://github.com/zenithdb/rfcs/pull/8)? Is there any other context around the idea of always putting data in s3 aside from the linked RFC?

I'm also thinking about case where customer has a local installation of zenith on their laptop. In that scenario it's my current understanding the user would have a local pageserver running on their laptop and they may want to push data from their local pageserver to a remote pageserver.

I'll bring this up during our meet today and follow up here

**Comment by patins** [comment]
Do we need to encrypt traffic between our VMs within a single cloud provider? I think we've said no before, but I'm wondering if AWS/GCP/Azure say it isn't needed

**Comment by hlinnaka** [comment]
> Do we need to encrypt traffic between our VMs within a single cloud provider? I think we've said no before, but I'm wondering if AWS/GCP/Azure say it isn't needed

I'm inclined to just require TLS everywhere. TLS encryption is pretty cheap these days. If the CPU consumption becomes an issue, we can make stop and think and make exceptions where it matters, later.

**Comment by mklgallegos** [comment]
+1 to TLS everywhere

Adding notes on customer perspective based on what I have seen in the past working with customers on database clusters.

Some customers need to enable intra cluster TLS (a requirement from their security team) and some customers don't care.

When enabling intra cluster TLS the main thing I think about is performance impact. It's important enabling intra cluster TLS doesn't cause a material performance impact. If it does we'll need to dig in.

**Comment by ericseppanen** [comment]
The tricky part of having nodes use TLS to talk to one another is certificate management. These nodes (e.g. pageservers) are short-lived, so there would need to be some kind of local certificate authority service to sign certificates for each node.

If communication always involves centralized, long-lived services, then it may be possible to avoid some of that by only having nodes talk to the central service (which could use real public CA certificates). This provides a secure connection, but does not provide any authentication of the node (to prove that the connection is from our pageserver, and not an imposter). If we wanted to use TLS to authenticate the node, then we'd need to issue client certificates to each node, and we're back to needing a private CA. Authentication could also be handled inside the TLS connection, using some kind of auth token we distribute to the nodes at creation.

AWS ACM would probably work fine as a private CA, but I haven't tried it myself.

**Comment by mklgallegos** [comment]
@patins - can you provide a rough estimate on how many days of effort this will take to complete (not including time waiting on reviews)
