### ISSUE TITLE
Proxy/routes for quick cluster access

### ISSUE THREAD

**Issue by mklgallegos** [zenithdb/zenith#292]
inital parts of the proxy machinery is done here:
https://github.com/zenithdb/zenith/compare/proxy

@kelvich when you have a chance can you add any additional context to this issue that you think might be helpful?

**Comment by kelvich** [comment]
Proxy will allow to create a cluster/database just by connecting to it without prior registration. New users would see the the link that they should press to confirm their identity and create a zenith account along the way. Users with installed access keys (~/.pgpass and ~/pg_servise files) would connect their database without the necessity to click the link -- so they can specify 'zenith.tech' in connection settings for IDE or app without prior database creation.

**Comment by kelvich** [comment]
![](https://raw.githubusercontent.com/zenithdb/console/main/docs/images/proxy.jpeg?token=AACFMO2WZGVTR47KDG6AAXLA43Q2G)

**Comment by mklgallegos** [comment]
linking documentation related to proxy:
https://github.com/zenithdb/console/blob/main/docs/proxy.md

**Comment by mklgallegos** [comment]
hi @kelvich when you have a chance can you provide a status update on this?

It would be helpful to know if this can be closed out or if there's work remaining. If there's work remaining can you describe it? (just checking on open issues in v0.1 milestone)

**Comment by kelvich** [comment]
I've just merged first part of proxy code: .

Few more open tasks about proxy (that would be good to have for v1):
https://github.com/zenithdb/zenith/issues/342
https://github.com/zenithdb/zenith/issues/282

and in console (less pressing imo):
https://github.com/zenithdb/console/issues/73
https://github.com/zenithdb/console/issues/75
https://github.com/zenithdb/console/issues/76

**Comment by mklgallegos** [comment]
hi @kelvich - this item was put into the done category during the milestone v0.2 planning session on 2021-07-30. I'm closing out. Please re-open if I am mistaken.
