### ISSUE TITLE
xl_prev handling

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#324]
pg_waldump and presumably postgres wal reader expect to see correct xl_prev in xlog record.
And we don't set it in WAL generated at compute node start. 

The simplest way to deal with it is to simply disable the check.

**Comment by mklgallegos** [comment]
@alubennikova  - this item was put in the done category during the milestone v0.2 planning session on 2021-07-30. I'm closing out. Please re-open if I am mistaken.
