### ISSUE TITLE
Remove twostate phase files correctly and the same way that other objects work

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#330]

**Comment by lubennikovaav** [comment]
@hlinnaka , this issue was created after your review of nonrel_wal PR. 
Can you remind, what was the issue?

I guess, the idea was to separate this logic from GC code and use put_unlink(twophase) on prepared_xact commit/rollback, right?

**Comment by hlinnaka** [comment]
> I guess, the idea was to separate this logic from GC code and use put_unlink(twophase) on prepared_xact commit/rollback, right?

That's right.
