### ISSUE TITLE
Store snapshots and WAL in separate files

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#339]
Currently, each "snapshot file" contains a base image of each page as of the file's start LSN, and WAL between start and end LSNs. That's cumbersome to create, because the page server needs to keep the "previous" snapshot in memory until the next snasphot happens. It would be better to write the WAL and the snapshot in separate files to avoid that. See "third option" at https://github.com/zenithdb/rfcs/blob/storage_architecture/snapshot-storage-pitr.md#third-option-not-implemented-yet

**Comment by mklgallegos** [comment]
related to #34
