### ISSUE TITLE
Storage format for the pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#34]
Right now everything is stored in-memory on pageserver. One way for persistency is just to have LSM of pages/records sorted by (db, ... , pageno, lsn). But own LSM sounds like a lot of works to do. Can we come up with something better/simpler here? And could we provide better performance compared to RocksDB?

**Comment by mklgallegos** [comment]
@ericseppanen when it makes sense can you break this issue down into several smaller issues?

**Comment by hlinnaka** [comment]
We no longer store everything in memory, closing.
