### ISSUE TITLE
Specify concrete name for superuser when initializing postgres data directory in pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#345]
initdb is a binary that ships with postgres and needed to initialize new postgres instance (or cluster or datadirectory in postgres terminology): https://www.postgresql.org/docs/13/app-initdb.html

By default it will create postgres superuser with name that is equal to username of current Unix user. And in our case that means that if we deploy pageserver under 'pageserver' Unix user we'll get postgres data directories with eponymous superuser name.

And compute node setup we need to access postgres via superuser role. Right now we hardcoded 'psgeserver' username, but that is installation-dependent. So ultimately it is better to override superuser with some pre-defined name ('postgres' or 'zenith_admin' or smth. else) during initdb itself.

We are running initdb inside of the pageserver here in src/branches.rs:42

So ultimately this task is about adding proper flag to `initdb` and checking that it actually helps with superuser name change -- manually and in python test.

**Comment by mklgallegos** [comment]
+1 for using `zenith_admin` as the pre-defined name
