### ISSUE TITLE
Import data in the pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#35]
Now pageserver accepts only incoming WAL. If we want to import/restore database in it we also need to accept just pages. I would model that as stored procedure that accepts pages via COPY protocol. Format may be just base backup data stream.

**Comment by lubennikovaav** [comment]
Done. See restore_s3.rs and restore_datadir.rs and test_upload_pageserver_local for details.

There is also a separate issue about code refactoring to make it extensible and support other data formats. See test_upload_pageserver_local for details:
