### ISSUE TITLE
Where to store config files?

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#355]
When you initialize a new compute node, where do you get the configuration files like postgresql.conf and pg_hba.conf?

If you run ALTER SYSTEM to change a setting, do we need to persist that somewhere in S3?

As of this writing, the config files are stored in the repository when the repository is initialized with 'zenith init'. In other words, you get the config that initdb generates. But that's about to change in https://github.com/zenithdb/zenith/pull/344.

This needs some design work..

**Comment by kelvich** [comment]
Right now console stores postgres config files as jsonb in the database and changes them only through the console -- users don't have superuser access to the database so they can't run ALTER SYSTEM. That is consistent with how other managed database players are handling configuration, so I think it is okay to not to store configs at pageserver.

That approach could be problematic if we allow postgres instances that aren't managed by us to connect to pageservers. But that functionality not in any planned milestone, so I would rather postpone that untile we actually decide to do that.

**Comment by lubennikovaav** [comment]
Readme about console compute settings management is here
https://github.com/zenithdb/console/blob/main/docs/compute_config.md

**Comment by mklgallegos** [comment]
This item was put into the done category during the milestone v0.2 planning session on 2021-07-30. I'm closing out. Please re-open if I am mistaken.
