### ISSUE TITLE
Compute (postgres) restart and start after a crash

### ISSUE THREAD

**Issue by ololobus** [zenithdb/zenith#369]
Currently restarting compute or starting after a crash is not entirely supported.

First one seems to work, as when we gracefully stop compute postgres then it will update its control file and write checkpoint record into WAL. So it will have all information needed for startup locally.

Yet latter is not that clear. Once postgres is get killed, control file continues to point to some old location, but this WAL may no longer be available locally. So the only reliable way to start compute again is to just dispose the entire data directory, do a fresh basebackup, apply config and finally start.

This could be acceptable but makes things much more cumbersome, because currently we control compute state inside VM / container using a `systemd` service, so it tries to restart postgres if it finds it dead. Yep, that could be configured as well, but then we will need an active monitoring daemon that will do this restart routine any time postgres is no longer available.

I do not want to say that this is not a solution, but personally I would prefer to handle the following situations in a more simple way from the control plane perspective:
- Config update. There are options that require server restart (`max_connections`, `shared_buffers`, and many other). And its tempting to do this operation in the same way as with original postgres
- Recovery after OOM killer comes and crash due to any other reason. IMO, it is nice to offload this to `systemd` instead of having an additional HA service even for handling such simple situations.

CC @lubennikovaav @kelvich @knizhnik (and anyone else), what do you think? Is it possible to teach postgres to do restart with some reasonable patch? Please, share your thoughts if any and/or correct me if I'm wrong.

**Comment by knizhnik** [comment]
Actually it is possible to support local restarts. Only two small changes are required:
1.Do not use "immediate" flag in stop and ignore stop error (already addressed by #368) 
2. Do not force wallogging page during shutdown (small patch for our zenith postgres extension)

**Comment by kelvich** [comment]
I think we can close that in favor of https://github.com/zenithdb/console/issues/119?

**Comment by ololobus** [comment]
Yeah, zenithdb/console#119 is a solution for this issue, at least for now. Closing
