### ISSUE TITLE
Store non-rel wal records on pageservers

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#40]

**Comment by knizhnik** [comment]
I have started implementation of first approach, adding support for pg_multixact, pg_xact, pg_filenode.map.
Them are updated at page_server when applying WAL and are included in tar file which is shipped to computation node at start.
We still have to include WAL in this tarball, although it is not strictly needed. I tried to generate dummy WAL using pg_resetwal utility, but it cause advancing LSN at compute node and so LSN mismatch between page_server and postgres.

**Comment by knizhnik** [comment]
I have changed RelTag class, moving forknum at the beginning of the  struct. It is needed to locate all pg_filenode.map files without traversing all page server database (it is <key,value>  database where key contains RelTag as prefix). So now ths pais will be first of all srted by fork number.

We are currently using special forknumber for non-rel files, i.e SRLU file, control file and pg_filenode.map files. I am not sure if it is the best solution, but other alternatives (suing special database/tablespace/relation ID seems to be even worse.

May be better solution is to add one more field: entity kind, i.e. relation, mxact_offset, mxact_members, clog, ...
But it requires rewriting a lot of code, so I am not filling ready for such massive changes without consultation and approval.

**Comment by mklgallegos** [comment]
Hi @knizhnik / @lubennikovaav 

When you have a chance can you provide following information:

1. general status update on this issue
2. any blockers?

I am asking because I noticed this issue is included in the v0.1 milestone and it looks like it hasn't been updated in awhile. Thank you

**Comment by kelvich** [comment]
Initial version was merged and we created bunch of follow up issues with `nonrel_wal` tag: https://github.com/zenithdb/zenith/issues?q=is%3Aissue+is%3Aopen+label%3Anonrel_wal

**Comment by kelvich** [comment]
So we can close that IMO
