### ISSUE TITLE
Safekeeper: "read from .../safekeeper.control" failed: deserialize error: failed to fill whole buffer

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#401]
That message pops up a lot in safekeeper logs. AFAIK that happens on the first access to the timeline and in reality that is just a misleading but not harmful error message. If that is the case let's fix that.

**Comment by arssher** [comment]
Already did that in #315

**Comment by kelvich** [comment]
@arssher is that merged?

**Comment by arssher** [comment]
Yes.
