### ISSUE TITLE
Make storage format code crash-safe

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#427]
- add CRCs to files to detect partial writes
- add fsync() calls where needed

the remainder of this task was moved over to #1083

**Comment by patins** [comment]
When should we `fsync` in the pageserver? With walkeepers and S3, is it ever necessary?

**Comment by kelvich** [comment]
> When should we `fsync` in the pageserver? With walkeepers and S3, is it ever necessary?

Failure scenario that would be good to have is protection from hard restart of physical host. If we know that data on the local disk is valid on some LSN we can use that files without loading them from S3 (that is possibly tens of TB).

So we can `fsync` all not yet synced files with lsn <= disk_consistent_lsn before updating timeline metadata with the new disk_consistent_lsn.

**Comment by patins** [comment]
Checksums have been added to metadata files, still waiting on review for the bookfile PR to get checksums for everything else

**Comment by stepashka** [comment]
there may be some fsyncs missing for s3
