### ISSUE TITLE
create_timeline errror: Failed to create tenant: psql: error: connection to server at "172.31.78.72", port 6400 failed: Connection timed out Is the server running on that host and accepting TCP/IP connections?

### ISSUE THREAD

**Issue by mklgallegos** [zenithdb/zenith#434]
Today 2021-08-17 I tried creating a cluster via web console (console.zenith.tech) and I noticed I was unable to run `select 1` against the cluster I created when.

I looked in the operations section and I noticed an error with the create_timeline action:
Failed to create tenant: psql: error: connection to server at "172.31.78.72", port 6400 failed: Connection timed out Is the server running on that host and accepting TCP/IP connections?

I was able to reproduce the issue with each cluster created.

attaching screenshots
<img width="1657" alt="Screen Shot 2021-08-17 at 12 21 22 PM" src="https://user-images.githubusercontent.com/15384251/129788498-68c91339-a593-4a53-9541-108fd9b90a5c.png">
<img width="1669" alt="Screen Shot 2021-08-17 at 12 21 51 PM" src="https://user-images.githubusercontent.com/15384251/129788506-467985c3-43f1-4714-9d61-20b4d21b8c6b.png">
<img width="1665" alt="Screen Shot 2021-08-17 at 12 22 11 PM" src="https://user-images.githubusercontent.com/15384251/129788511-8c047cb1-b789-4bfc-8bb8-2a15e79318ba.png">

**Comment by kelvich** [comment]
fixed
