### ISSUE TITLE
Compute node restart when safekeeper flush_lsn > VCL

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#439]
If we'll try to properly ask safekeepers about flush_lsn/VCL (https://github.com/zenithdb/console/issues/127) we can stuck in a basebackup from pageserver as there is no guarantee that pageserver is connected to the safekeeper with maximal VCL. Moreover, we don't have any code to replay piece of WAL between VCL and flush_lsn.

More discussion is in https://discord.com/channels/869525774699462656/877123107448565801/877123110904668161

Out of all the options we decided to use current wal_proposer in postgres to perform synchronization of safekeepers: properly acquire term/generation and commit all the WAL between VCL and flush_lsn on all (majory) safekeepers. After that we can start postgres (we also need to ensure that LSN didn't change in between). Current plan is to write one more separate main function that would call wal_proposer code.

**Comment by knizhnik** [comment]
This is how walproposer should be started before basebackup in tests to sync safekeepers:
```
    sh -c "cd zenith_tmp/compute && VCL=`PGDATA=zenith_tmp/compute postgres --sync-walkeepers` && psql -p6400 -hlocalhost -Xqtc 'basebackup ${TENANT_ID} ${TIMELINE} ${VCL}' | tar -x"
```
