### ISSUE TITLE
Decoding xl_heap_delete and xl_heap_update structs is missing t_cid field

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#461]
In waldecoder.rs:
```
 pub struct XlHeapDelete {
     pub xmax: TransactionId,
     pub offnum: OffsetNumber,
     pub infobits_set: u8,
     pub flags: u8,
 }
```
But the corresponding Postgres struct in heap_xlog.h looks like this:
```
/* This is what we need to know about delete */
typedef struct xl_heap_delete
{
	TransactionId xmax;			/* xmax of the deleted tuple */
	OffsetNumber offnum;		/* deleted tuple's offset */
	uint32      t_cid;
	uint8		infobits_set;	/* infomask bits */
	uint8		flags;
} xl_heap_delete;
```
The Rust version is missing the t_cid field. Because of that, we won't read the XLH_DELETE_ALL_VISIBLE_CLEARED flag in 'flags' correctly, and might fail to clear the VM bit correctly,

I suspect that this explains https://github.com/zenithdb/zenith/issues/460, but I'm opening a new issue because I'm not sure.

**Comment by kelvich** [comment]
#460 reproduces on my laptop and with following patch:
```
diff --git a/pageserver/src/waldecoder.rs b/pageserver/src/waldecoder.rs
index bc072ff..874bb3c 100644
--- a/pageserver/src/waldecoder.rs
+++ b/pageserver/src/waldecoder.rs
@@ -368,6 +368,7 @@ impl XlHeapMultiInsert {
 pub struct XlHeapDelete {
     pub xmax: TransactionId,
     pub offnum: OffsetNumber,
+    pub t_cid: u32,
     pub infobits_set: u8,
     pub flags: u8,
 }
@@ -377,6 +378,7 @@ impl XlHeapDelete {
         XlHeapDelete {
             xmax: buf.get_u32_le(),
             offnum: buf.get_u16_le(),
+            t_cid: buf.get_u32_le(),
             infobits_set: buf.get_u8(),
             flags: buf.get_u8(),
         }
```

test is working. So probably that was the reason.

**Comment by hlinnaka** [comment]
> #460 reproduces on my laptop and with following patch:
> 
> ```
> diff --git a/pageserver/src/waldecoder.rs b/pageserver/src/waldecoder.rs
> index bc072ff..874bb3c 100644
> --- a/pageserver/src/waldecoder.rs
> +++ b/pageserver/src/waldecoder.rs
> @@ -368,6 +368,7 @@ impl XlHeapMultiInsert {
>  pub struct XlHeapDelete {
>      pub xmax: TransactionId,
>      pub offnum: OffsetNumber,
> +    pub t_cid: u32,
>      pub infobits_set: u8,
>      pub flags: u8,
>  }
> @@ -377,6 +378,7 @@ impl XlHeapDelete {
>          XlHeapDelete {
>              xmax: buf.get_u32_le(),
>              offnum: buf.get_u16_le(),
> +            t_cid: buf.get_u32_le(),
>              infobits_set: buf.get_u8(),
>              flags: buf.get_u8(),
>          }
> ```
> 
> test is working. So probably that was the reason.

You missed the padding before 't_cid', so that's still not actually decoding it right. See https://github.com/zenithdb/zenith/pull/462. Maybe it was still the same bug and this still fixes it, not sure?

**Comment by kelvich** [comment]
> You missed the padding before 't_cid', so that's still not actually decoding it right. See #462. Maybe it was still the same bug and this still fixes it, not sure?

Yeah, right. Test in #462 was able to catch missing `buf.get_u16_le()`
