### ISSUE TITLE
Graceful shutdown of the page server

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#477]
If the page server is shut down gracefully, e.g. by SIGTERM, it should flush any remaining data in-memory to disk before exiting. And also upload everything to S3 (although S3 upload hasn't been implemented as of this writing).

**Comment by lubennikovaav** [comment]
Our thread model right now is:

main `pageserver` daemon
- `WAL receiver thread` 
- `http_endpoint_thread` thread that serves incoming requests
- `page_service`  Listens for connections, and launches a new handler thread for each.
  - `conn_handler` Per connection handler.

- per_tenant threads
  - `Checkpointer thread` Flush in-memory layers to disk. *
  - `GC thread` Remove on-disk layers that are not visible anymore.
  - `relish_uploader` Send layer files to S3 (or other object storage).
  - `wal_redo_manager` Runs postgres binary in wal-redo mode.

*see also #648
