### ISSUE TITLE
Create LSN datatype

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#49]
This pattern is quite tedious:
```
format!("current LSN is {:X}/{:X}", lsn >> 32, lsn & 0xffffffff);
```
We should have a datatype with `Display` trait, so that you could write just:
```
format!("current LSN is {}", lsn);
```

**Comment by ericseppanen** [comment]
There is a `PgLsn` struct in the `postgres` crate today ([source](https://docs.rs/postgres-types/0.2.1/src/postgres_types/pg_lsn.rs.html#14)). Looks like they already have the `Display` impl exactly as you wrote it here (but should it be `{:X}/{:08X}`?)

If we want to implement our own `Lsn` type, that code is a good model of how to do it.
