### ISSUE TITLE
Flaky error in test_pageserver_restart in CI

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#500]
Found in #499 

In pageserver logs:
```
Aug 31 09:10:21.514 ERRO get_page_at_lsn: no base img found for 1663/13974/2662.0 at blk 0 at LSN 0/2763E78, location: pageserver::page_service, pageserver/src/page_service.rs:313
```
In pg logs:
```
2021-08-31 09:10:21.510 GMT [2033] LOG:  [ZENITH_SMGR] libpqpagestore: connected to 'host=localhost port=64000 password='
2021-08-31 09:10:21.514 GMT [2033] FATAL:  could not read block 0 in rel 1663/13974/2662.0 from page server at lsn 0/02763E78
```
Error happened only in debug, release test succeeded

> @patins noted that last night, too. It's happened a few times in the CI on 'main'. He suspected commit 7c7e89e as the culprit, because it didn't happen before that, although it's hard to tell because it doesn't happen very often.

**Comment by hlinnaka** [comment]
My first thought was that we can fix this in `InMemoryLayer::put_page_version`: If the segment is being extended by more than one page, implicitly fill the gap with all-zeros pages. That's analogous to what PostgreSQL does with local filesystem.

However, it's not that simple if the gap block is at a segment boundary. For example, if a table is extended from 1279 to 1281, by writing to block no 1280. Block no 1279 should be filled with zeros, but that's on segment 0, while block 1280 is on segment 1. `InMemoryLayer::put_page_version` will be called on segment 1, and we cannot change segment 0 there. We will need to coordinate this from `LayeredTimeline::put_wal_record` somehow.
