### ISSUE TITLE
prev_record_lsn for branching with old lsn

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#506]
I've added some debug output to create_branch. Seems that we take recent prev_record_lsn even while branching with some old LSN (note that prev_record_lsn >  disk_consistent_lsn).

```
> ./target/debug/zenith branch mybr main@0/3000000  
<...>
Aug 31 23:24:45.919 INFO saving metadata ./tenants/290da579425188b18af3f6cbb0332c0b/timelines/778b23f037d6e415c019b81599bf5a91/metadata: 
TimelineMetadata {
disk_consistent_lsn: 0/3000000,
prev_record_lsn: Some(0/3DFA4FD),
ancestor_timeline: Some(ZTimelineId(ZId([41, 143, 105, 64, 104, 62, 247, 236, 238, 177, 169, 248, 39, 239, 68, 151]))), ancestor_lsn: 0/3000000 },
location: pageserver::layered_repository, pageserver/src/layered_repository.rs:299
```

compute node on that branch will fail while right on the start while reading zenith.signal (which would be set to prevLsn):

```
> hexdump -v -e '4/4 "%X\t"' .zenith/pgdatadirs/tenants/290da579425188b18af3f6cbb0332c0b/mybr/zenith.signal
3DFA4FD	0

> cat pg.log
PANIC:  invalid redo record in shutdown checkpoint
```

while controldata points to 0/3000000:
```
pg_control last modified:             Tue Aug 31 23:19:24 2021
Latest checkpoint location:           0/3000028
Latest checkpoint's REDO location:    0/3000000
```

It is also interesting why test_branch_behind.py misses that

**Comment by knizhnik** [comment]
I have searched how xl_prev is used in Postgres and find out that:
1. Only pg_rewind is using it for backward iteration to locate last checkpoint record.
2. xlog reader is checking that xl_prev < RecPtr for "random" access (when there is no previous record) and xl_prev == PrevRecPtr for streaming.

Right now we correctly initialize  xl_prev for started compute node if it is launched from last WAL position. It is done through zenith.signal file. If we try to create branch for some previous LSN, then we do not know xl_prev.

What can be done?
1. Prohibit PiTR: branches can be only created on last LSN and so we can provide recovery only to some preexisted points (snapshots).
2. Delete checks for xl_prev and prohibit pg_rewind
3. Delete xl_prev at all and save 8 bytes per wal record.
4. Maintain map of lsn->xl_prev for PiTR interval in pgaeserver (it has to be persisted in case of pageserver restart)
5. Locate previous LSN by traversing WAL. Looks like it has to be done by pageserver, which should request relevant WAL segments from safekeeper which in turn should retrieve missed segments from S3. We can start from the begging of last WAL segment, if it contains no record start, then loop back to the repviosu segment and so on...

If we remove xl_prev or store invalid value in it, then we loose compatibility of WAL format with vanilla Postgres and possibility to stream WAL to some external wal readers (not patched by us).

Thougts?

**Comment by kelvich** [comment]
I would propose another option:

6. Can't we just set xl_prev to 42 or last_lsn-1 when creating branch@old_lsn and keep checks as they are? That fake prev_lsn is needed only for the first record in the branch. And that WAL segment is anyway not readable by pg_waldump (can be read with the right offset).

Also I don't understand reference to `pg_rewind` in this context -- we don't have any WAL before checkpoint so there is no way for it to work.

**Comment by knizhnik** [comment]
6) will not pass check in walreader.  I.e. we are not able to stream this WAL to replica.

> we don't have any WAL before checkpoint so there is no way for it to work.
At safekeeper we have all WAL before and after this point. Moreover, old and new parts of WAL are seamless concatenated. So, if we correctly set xl_prev,then WLA at safekeepers will be the same as if it was produced at local node (except first segment).

**Comment by kelvich** [comment]
We talked a bit about basebackup. Seems that basebackup@old_lsn is entirely unnecessary thing. If we want to create branch we need to call create_branch first and it would initialize last_record_lsn. So we may take basebackup @last_record_lsn in all of the situations. basebackup@lsn is only needed to wait for lsn (and we should throw an error requested_lsn < last_record_lsn).

Only one thing that we need to distinguish is whether current basebackup is taken on newly created branch or not. In the first case prev_lsn is None and we need to pass it down to compute node and teach it to work with.

**Comment by hlinnaka** [comment]
On 01/09/2021 16:02, Stas Kelvich wrote:
> We talked a bit about basebackup. Seems that ***@***.***_lsn is 
> entirely unnecessary thing. If we want to create branch we need to call 
> create_branch first and it would initialize last_record_lsn. So we may 
> take basebackup @last_record_lsn in all of the situations. 

It's needed for creating a read-only node. Sure, you can create a branch 
and then launch the server against that, but that won't work for 
creating a read-only replica follows the primary.

Granted, we don't have the code to create such a replica yet :-).

> ***@***.*** is only needed to wait for lsn (and we should throw an 
> error requested_lsn < last_record_lsn).
> 
> Only one thing that we need to distinguish is whether current basebackup 
> is taken on newly created branch or not. In the first case prev_lsn is 
> None and we need to pass it down to compute node and teach it to work with.

If the compute node can deal with None, that's great. Then we can pass a 
None for the ***@***.***_lsn case, too. Or even always?

- Heikki

**Comment by kelvich** [comment]
> It's needed for creating a read-only node

Yeah, we can add some parameter indicating that it is okay to respond with invalid prev_lsn when we are not at the beginning of the branch (only use case would be RO replica).

> If the compute node can deal with None, that's great. Then we can pass a None for the ***@***.***_lsn case, too. Or even always?

Seems that github thinks that our command syntax is email addresses =) Always passing None to the compute node would leave records with bad prev_lsn in the WAL after each restart. So makes sense to restrict that only for new branches and RO replicas (which anyway would not produce any WAL).

**Comment by knizhnik** [comment]
So two fixes are suggested:
1. Fix assignment of prev record LSN for created timeline. It should use prev_rec_lsn from spurce timeline only of we branch on the lat record.
2. Check that LSN passed to basebackup equals to last_rec_lsn, otherwise report error
I have implemented 1) in https://github.com/zenithdb/zenith/pull/516 and  2) is postponed until last_valid_lsn will be replaced with last_record_lsn (https://github.com/zenithdb/zenith/commit/5a4e90c3d5fd0bb8b0d1ec5a6f3ab9d8f4be6ecd)

**Comment by knizhnik** [comment]
Concerning original issue of the ticket:
Error message `PANIC:  invalid redo record in shutdown checkpoint` is produced only if there is not zenith.signal file which is always included in basebackup. So something is wrong with the way compute node is launched.
This is why test_branch_behind passed (the fact the xl_prev is greater than current LSN is not checked during startup, but if you try to stream WAL from this record, then "invalid record" will be reported.
