### ISSUE TITLE
Add a header with some metadata to layer file format

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#519]
Currently, the segment tag, start and end LSN are only stored as part of the filename. That works, but some redundancy would be nice, so that if you copy and rename a layer file, you could still extract that information from the file itself. That would be nice for the `dump_layerfile` utility. Secondly, you could cross-check that information with the filename when reading a file in the page server.

A CRC would be good too, to detect corrupt files (see also https://github.com/zenithdb/zenith/issues/427)

**Comment by patins** [comment]
Metadata included with #621.
Moving checksum work to bookfile
