### ISSUE TITLE
Error propagation in pageserver http api/cli

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#525]
Trying to create branch with the same name again:

```
`--> ./target/debug/zenith branch br main                                                            
Created branch 'br' at 0/16B9150 for tenant: fdc09209aa9bd8c6f39162a9a9067feb

`--> ./target/debug/zenith branch br main
branch command failed: HTTP status server error (500 Internal Server Error) for url (http://127.0.0.1:9898/v1/branch)
```

**Comment by LizardWizzard** [comment]
Yeah, thought about that. That's because we don't make a distinction between our application level errors, http handler can only see anyhow::Error without a clear cause. Probably worth looking at thiserror crate for that purpose

**Comment by kelvich** [comment]
> Yeah, thought about that. That's because we don't make a distinction between our application level errors, http handler can only see anyhow::Error without a clear cause

But error text is available and it provides enough context for some popular scenarios. So returning the text along with http status and showing it to the user should help.
