### ISSUE TITLE
Safekeeper metrics

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#541]
Add same http server with `/metrics` endpoint.

per-tennat metrics:
* flush_lsn
* commit_lsn
* pageserver feedbacks
* time to fsync -- histogram

**Comment by yeputons** [comment]
This is my first onboarding task.

Steps discussed with Stas (`@kelvich`):

1. Add `listen_addr` to Safekeeper's config. 
2. Add a `Hello world` HTTP server to Safekeeper. One can take a look at something like `http_endpoint.rs`/`make_router` around zenith-utils and how it's used in Pageserver. 
3. Add a `Hello world` gauge metric.
4. Add `flush_lsn`, `commit_lsn` metrics as gauges. Thing to consider: do we want to have a metric shadow internal state of Safekeeper or do we want to read the state inside the `/metrics` URL handler?

**Comment by yeputons** [comment]
I've discovered #663 while digging into HTTP endpoints. I'm working in the [`safekeeper-metrics-541` branch](https://github.com/zenithdb/zenith/tree/safekeeper-metrics-541), which is based on the PR above.

At the moment it looks like HTTP metrics are working, but:

* The common code provides a bunch of default metrics starting with `pageserver_`: [one](https://github.com/zenithdb/zenith/blob/d749f975ced918f72b0566fc47eba1b984d1a2c6/zenith_metrics/src/lib.rs#L27-L34), [two](https://github.com/zenithdb/zenith/blob/d749f975ced918f72b0566fc47eba1b984d1a2c6/zenith_utils/src/http/endpoint.rs#L17-L23). I think both are worth either renaming to something more generic or adding an extra configuration key.
* Calling `register_int_gauge` only creates a manually-update gauge. For example, one is automatically updated on all metrics requests by some hard code [here](https://github.com/zenithdb/zenith/blob/c846a824ded8404d82dd0a61f6c7de65d6e1234d/zenith_utils/src/http/endpoint.rs#L36) and [there](https://github.com/zenithdb/zenith/blob/d749f975ced918f72b0566fc47eba1b984d1a2c6/zenith_metrics/src/lib.rs#L23). However, one can implement the [`Collector` trait](https://docs.rs/prometheus/0.12.0/prometheus/core/trait.Collector.html) and call [the `register` function](https://docs.rs/prometheus/0.12.0/prometheus/fn.register.html) directly.

It _may be_ a good idea to a) rewrite the current gauge via `Collector` trait to avoid hard-coding; b) provide a macro similar to `register_int_gauge` for doing so; c) upstream such macro to the `prometeus` library. The alternative is to shadow the gauge.

**Comment by yeputons** [comment]
As metrics are per-tenant (per-timeline, more precisely), it may be ineffective to update them from the `gather()` method; it requires traversing all timelines under mutex.

So I'm manually updating gauges whenever required:

* `flush_lsn` is only updated in a single place
* `commit_lsn` exists in three versions: one is probably unrelated to this issue (see #682), one is the important one (only changed in a single place), and the last one keeps track of the control file (again, unrelated).

As of a4792818850533e95ec4a437f6eda6aed67e2cb7 tests are green.

I don't think getting rid of `zenith_metrics::gather()` in favor of implicit rlimits collection via the `Collector` trait is a good idea. It doesn't look like we're going to use anything else than `zenith_utils::http::endpoint()`, and it's easy to make explicit collection here.

Next possible steps are to be discussed:

* Make sure `ZTimelineId` is reported as `u64`, not as a `i64`
* Add some tests to ensure metrics are reported and collected. For example, `test_normal_work` results in `commit_lsn==flush_lsn==48432120` right before the test starts to complete, and it bumps up to `48432176` as it's stopping. That's about 50 MB on a table with 10^5 `(int, text)` rows. I'm not sure how reliable these numbers are expected to be.
* Adding pageserver feedbacks metric
* Adding time to fsync histogram

**Comment by yeputons** [comment]
> Make sure ZTimelineId is reported as u64, not as a i64

I'd actually keep it `f64`. On my local VM, `i64` gauge is twice as fast as `f64` (5 ns per increment vs 10 ns, if I'm reading prometheus' benchmarks correctly), so `u64` gauge may be fast as well. However, I think adding code to Prometheus-Rust is out of scope at the moment. I left a comment.

**Comment by yeputons** [comment]
> Add some tests to ensure metrics are reported and collected.

As I was told in the chat by @knizhnik, LSNs are

> Absolutely non-deterministic. There are some postgres background activities like vacuum, checkpointer which are also writing WAL.

but @arssher thinks that

>It is more or less ok to rely on known workload to take at least n bytes - WAL hardly would get significantly more compact over time, but concrete LSN doesn't sound like a good idea.

So I would still add some methods to retrieve LSNs in test just to make sure metrics are not broken. However, I would put very relaxed assertions like "metrics are available", "greater than zero", "changed by at least 1000"
