### ISSUE TITLE
safekeeper: align commit_lsn on completed record boundary

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#549]

**Comment by hlinnaka** [comment]
Why? (Just curious..)

**Comment by kelvich** [comment]
Idea is that VCL (now referred as commit_lsn in safekeeper code) should never go backwards. And if we allow for commit_lsn to be advanced to incomplete record we may end up in a situation where postgres is restarted without completing that record. On the next start postgres will try overwrite that incomplete record which was committed in quorum sense (some safekeepers may already advanced commit_lsn past it start).

To fix that we can just never advance commit_lsn in the middle of the record -- keep it pointing to the end of the latest complete record.

Maybe word "align" is misleading in this context.
