### ISSUE TITLE
Compute node can request an old page version that has been GC'd away already

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#567]
Sequence of events:

1. Compute node generates a bunch of WAL, between say LSN 1000-2000. There is one change to relation A at LSN 1100, the other changes are to relation B
2. Page server receives and processes it.
3. Checkpoint in page server freezes the in-memory layer for relation A into a delta layer 1000-1200 and new image layer at 1200.
4. Page serve runs Garbage collection, with GC horizon 500, removing anything older than LSN 1500. So it removes the delta layer 1000-2000 and leaves only image layer at 1200
4. Compute node makes a GetPage@LSN request with LSN 1000. It does that because it hasn't yet evicted any pages from the buffer cache between 1000-2000, and it always uses the oldest evicted LSN in the request
5. Page server doesn't find the requested page, because it seems to have been garbage collected away already. In reality, there haven't been any changes to the requested page, but the page server doesn't know that.

To fix this, I think we need to add a flag to GetPage@LSN call to distiguish two cases: a) read-only nodes that need to fetch the page version at the specific LSN, and b) primary that's generating WAL, and needs to read the most recent version of the page, but provides the LSN as a hint that it knows that the page hasn't changed since that LSN and so the page server doesn't need to wait for newer WAL to be processed.

I bumped into this in the 'pgbench' performance tests with this PR: https://github.com/zenithdb/zenith/pull/562, but I'm pretty sure it's a pre-existing bug.

**Comment by lubennikovaav** [comment]
Is it the same issue as #95?

**Comment by hlinnaka** [comment]
> Is it the same issue as #95?

Not quite. #95 is about giving a nicer error message if you request a page that's already been garbage collected away. That happens with this bug. But it shouldn't be happening in the first place

**Comment by hlinnaka** [comment]
Here's a test case for this

[test_old_request_lsn.py.txt](https://github.com/zenithdb/zenith/files/7146055/test_old_request_lsn.py.txt)
