### ISSUE TITLE
Relation extension after truncation doesn't work

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#569]
It is possible that we dropped a relish and then created it again within the same InMemoryLayer.
What is the meaning of `drop_lsn` then? Now we just don't see the version of the segment after drop.

How should we treat the same scenario in a delta layer?
What if we will drop this relish once more?

I wrote two tests to illustrate the problem:
#568
`RUST_BACKTRACE=1 cargo test test_drop_extend` is a bit synthetic. 
I cannot come up with a realistic workload where we create relish shortly after it was dropped. In theory, it may happen in the case of SLRU wraparound.  And I think it is a reason why #403 fails.

`RUST_BACKTRACE=1 cargo test test_truncate_extend` simulates more realistic example of workload.

**Comment by petergeoghegan** [comment]
@alubennikova Why is it okay that we don't do anything with relmapper.c in zenithdb? Have you seen any failures involving VACUUM FULL or CLUSTER specifically?

**Comment by kelvich** [comment]
> @alubennikova Why is it okay that we don't do anything with relmapper.c in zenithdb? Have you seen any failures involving VACUUM FULL or CLUSTER specifically?

We put 'pg_filenode.map' into postgres data directory before compute node start. See RelishTag::FileNodeMap in pageserver -- we intercept WAL that changes FileNodeMap and maintain it up to date.
