### ISSUE TITLE
Questions about layered repository terminology

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#571]
1. Is there any difference in the meaning between `open` layer and the `in-memory` layer?

2. Let's clarify the meanings of `Segment` and `Layer` terms.

`Segment` (Seg*) refers to a slice of relish (defined by a SegmentTag) and `Layer` corresponds to the specific version of the segment in some LSN range.
Is it ok?

3. Is there any difference between layer.is_dropped() and layer.get_seg_exists(self.end_lsn) ?

**Comment by hlinnaka** [comment]
>     1. Is there any difference in the meaning between `open` layer and the `in-memory` layer?

Currently no. However, see https://github.com/zenithdb/zenith/pull/572, that introduces a new kind of layer, the "FrozenLayer", which is in-memory but cannot be modified. In principle, "open" means that the layer can still be modified, and "in-memory" means that it's not stored on disk, so they are not the concepts even though those two properties currently go hand in hand. Let's keep them separate, but let's explain that in the comments and and glossary.

>     2. Let's clarify the meanings of `Segment` and `Layer` terms.
> 
> 
> `Segment` (Seg*) refers to a slice of relish (defined by a SegmentTag) and `Layer` corresponds to the specific version of the segment in some LSN range.
> Is it ok?

Yep.

>     1. Is there any difference between layer.is_dropped() and layer.get_seg_exists(self.end_lsn) ?

Hmm, I guess not. An open layer doesn't have an `end_lsn`, though.
