### ISSUE TITLE
Lots of CPU time spent in formatting ZTimelineId

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#622]
In testing a bulk load scenario:
```
create table huge (i int, j int);
insert into huge values (generate_series(1,100000000), 0);
```
A large amount of CPU time is spent on converting ZTimelineId to string:
![image](https://user-images.githubusercontent.com/191602/133771024-3688f6cd-6946-4637-a6d1-7ae74f75fe00.png)

That's coming from here:

```
    ///
    /// This is a helper function to increase current_total_relation_size
    ///
    fn increase_current_logical_size(&self, diff: u32) {
        let val = self
            .current_logical_size
            .fetch_add(diff as usize, Ordering::SeqCst);
        trace!(
            "increase_current_logical_size: {} + {} = {}",
            val,
            diff,
            val + diff as usize,
        );
        LOGICAL_TIMELINE_SIZE
            .with_label_values(&[&self.tenantid.to_string(), &self.timelineid.to_string()])
            .set(val as i64 + diff as i64)
    }
```
And in particular, the `self.tenantid.to_string()` and `self.tenantid.to_string()` calls.

**Comment by knizhnik** [comment]
Can it be explained by using debug build?
Debug version of to_string functions is 15 times slower!
0.14 usec vs. 3 usec

**Comment by hlinnaka** [comment]
I was using a release build

**Comment by knizhnik** [comment]
This version is 5 times faster:
```
fn to_hex(c: u8) -> u8 {
	if c > 9 {
		c + b'A' - 10
	} else {
		c + b'0'
	}
}
impl fmt::Display for ZId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		let mut buf = [0u8; 32];
		for i in 0..16 {
			buf[i*2] = to_hex(self.0[i] & 0xF);
			buf[i*2+1] = to_hex((self.0[i] >> 4) & 0xF);
		}
		unsafe {
			f.write_str(std::str::from_utf8_unchecked(&buf))
		}
//		f.write_str(&hex::encode(self.0))
    }
}
```

**Comment by hlinnaka** [comment]
Yeah, Rust's philosophy of zero-cost abstractions isn't really working here :-D.

I think we should avoid formatting those strings in the first place. We could fetch the reference to the prometheus Metric for this timeline only once, with `MetricVec::get_metric_label_values`, and store it in the `LayeredTimeline`. Then `increase_current_logical_size` could do something like `self.size_gauge.set(val as i64 + diff as i64)`.

**Comment by sharnoff** [comment]
I just played around, trying to find some possible other solutions and I think @knizhnik's code is as fast as it can be.

(Although note: the write orders should be swapped on little-endian machines, with `buf[i*2] = to_hex((self.0[i] >> 4) & 0xF)`)
