### ISSUE TITLE
Fix blocking call to PQgetCopyData in libpagestore

### ISSUE THREAD

**Issue by petuhovskiy** [zenithdb/zenith#644]
Test `test_restarts_under_load` failed in CI with error `pg_ctl: server does not shut down`
- [CI job](https://app.circleci.com/pipelines/github/zenithdb/zenith/1975/workflows/6121d973-cfb9-4534-b031-5056113d6bc2/jobs/13499/steps) 
- [pg.log](https://13499-351806852-gh.circle-artifacts.com/0/tmp/test_output/test_restarts_under_load/repo/pgdatadirs/tenants/69a95ce8011bad19d9bf9178184751aa/test_wal_acceptors_restarts_under_load/pg.log)

As discussed with @arssher, the following happens:
- test writes a lot of data and trigger vacuum operations
- test finishes
- safekeepers are shutting down
- vacuum operation is running in the background and communicates with pageserver
- `zenith pg stop` tries to shut down compute node
- compute node can't cancel vacuum and waits for pageserver
- pageserver waits for WAL from safekeeper, but it's already down 
- pg_ctl is stopping postgres and fails after one minute because of shutdown timeout

To fix this, we need to fix blocking call to [PQgetCopyData](https://github.com/zenithdb/postgres/blob/452b7abaabea107a88df3d9037d65b1b7c532349/contrib/zenith/libpagestore.c#L243), which should stop waiting for response on shutdown.

**Comment by hlinnaka** [comment]
PQgetCopyData was made interruptible by commit a504cc87ab2693eaf8a5bd5131cb8261f64a04e5. Closing.
