### ISSUE TITLE
Track memory usage

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#656]
Investigate memory usage in Page server.

- How much is spent on which layer? Are there leaks?
- Add counters for tracking the memory usage and expose them as prometheus metrics.
- Perform checkpointing based on memory usage.
- Pause receiving WAL if too much memory is already used.

**Comment by patins** [comment]
Ok to close @hlinnaka

**Comment by hlinnaka** [comment]
Much of this has been done, or obsoleted by other changes. Closing.
