### ISSUE TITLE
Add performance test for tenant start

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#672]
Measure the time from clicking "start" to first query, as part of the perf test suite

**Comment by cicdteam** [comment]
Just realized that tenant creation time raised in 2-2.5 times (from 1.6-2.0 seconds to 4-5 seconds) after 62f8386 commit in main branch.

- in commit 69670b6 average tenant creation time is ~2 sec
- in commit 62f8386 average tenant creation time is ~4.4 sec

seems additional fsync affect it. @patins can confirm I think.

**Comment by patins** [comment]
Yeah I think this would be possible due to the number of layer files that are created on init. It'd be nice if we could sync all of the files at the end instead of syncing each one sequentially
