### ISSUE TITLE
WAL Safekeeper's FileStorage::persist may theoretically leave control file corrupt

### ISSUE THREAD

**Issue by yeputons** [zenithdb/zenith#678]
I suppose [this `persist` function](https://github.com/zenithdb/zenith/blob/6d993410c98a67043eaad2f1be2adccf1b7808e9/walkeeper/src/timeline.rs#L331-L338) is assumed to be atomic. However, it overrides the existing file. If something fails during the write, the file may be left corrupted because some changes have reached the filesystem and some are not.

Possible fix is (at least according [to the discussion here](https://users.rust-lang.org/t/how-to-write-replace-files-atomically/42821/13)) to write to a temporary file on the same filesystem (i.e. not just `/tmp`), sync it, atomically rename it, sync the folder.

**Comment by patins** [comment]
It also seems like if a future serialization is longer than the current one, there may be leftover bytes not used by the deserializer
