### ISSUE TITLE
Rename walkeeper's `SharedState::commit_lsn` to avoid confusion

### ISSUE THREAD

**Issue by yeputons** [zenithdb/zenith#682]
As @kelvich and I discussed today, [`SharedState::commit_lsn`](https://github.com/zenithdb/zenith/blob/6d993410c98a67043eaad2f1be2adccf1b7808e9/walkeeper/src/timeline.rs#L35) looks like it's only used to synchronize some multithread data flows inside the safekeeper binary. However, it can be confused with [`SafeKeeperState::commit_lsn`](https://github.com/zenithdb/zenith/blob/6d993410c98a67043eaad2f1be2adccf1b7808e9/walkeeper/src/safekeeper.rs#L73-L74) which is actually part of the consensus protocol.

How about the former is renamed to something else? I'm not sure what it's used for, but maybe something like `max_proposer_acceptor_commit_lsn` or `max_proposed_commit_lsn` would be better.

**Comment by arssher** [comment]
Renamed it to `notified_commit_lsn`. Just to be clear, semantically this is the same variable; we just cache the value with which we did `notify_all` the last time to avoid repeating that pointlessly.
