### ISSUE TITLE
Write amplification due to always evicting oldest layer at checkpoint.

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#710]
In page server, checkpointing currently works on an oldest-first policy. We hold a fixed amount of WAL in in-memory layers (DEFAULT_CHECKPOINT_DISTANCE, 256 MB), and anything older than that is written out to disk as delta+image layers.

The oldest-first policy can lead to huge write amplification, if the distribution of WAL is skewed, so that you have a lot of WAL records affecting a small number of segments, and random updates across many other segments. The bulk of the WAL that affects only a few segments causes the checkpoint distance to be reached quickly, and that forces new image layers to be generated for all the other segments too, even though there have been only little changes in them.

On discord, @petergeoghegan mentioned a research paper that's relevant here: https://arxiv.org/pdf/2005.00044.pdf.

**Comment by stepashka** [comment]
We're going forward with the LSM approach, see #936 , so this doesn't see to be relevant anymore.
