### ISSUE TITLE
Avoid running concurrent checkpointing + gc

### ISSUE THREAD

**Issue by patins** [zenithdb/zenith#713]
It's not safe to have concurrent checkpointers running for a timeline. 

Simple solution is probably just wrapping checkpoint routine with a Mutex?

Maybe GC is safe because a lock is held for the duration?

**Comment by stepashka** [comment]
@patins was this done already? @hlinnaka mentioned that he thinks we don't have this issue anymore

**Comment by patins** [comment]
Concurrent checkpoints are still possible, they are executed by at least: checkpointer loop thread, timeline shutdown, GC w/ checkpoint_before_gc = true.

I never figure out if concurrent checkpoint + GC is safe, that might still be an issue as well
