### ISSUE TITLE
Safekeeper sets Postgres timeline ID to 0

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#824]
I've hit one problem that's potentially unsolvable without backwards incompatibilities: PostgreSQL relies on pg's TimeLineID always being >0, i.e. the initial timeline ID of a freshly initialized cluster is 1. The Safekeeper initializes this to 0. As a result, I cannot start nodes in replication mode, because the safekeeper has a lower timeline identifier than that what postgresql has.

I could hack around that in the WAL receiver infrastructure in PG, but I don't think that is smart. Instead, I could replace all occurances of TLI == 0 with TLI == 1, which I think is a more ergonomic option.

_Originally posted by @MMeent in https://github.com/zenithdb/zenith/issues/769#issuecomment-957866095_

**Comment by hlinnaka** [comment]
@arssher, can you take a look at this please? Or reassign to someone.

@MMeent, can you elaborate, where does the safekeeper set the postgres timeline id? Is it present in the streaming replication messages, or in the WAL page headers, or where?

**Comment by MMeent** [comment]
According to further research on how walkeeper gets the TLI, it receives it from the greeting message; which contains the value of `ThisTimeLineID` (see xlog.h), which is uninitialized for both `--sync-walkeepers` and when the walsender starts up.

**Comment by arssher** [comment]
Changing PG timeline is not really supported, and it is not even clear what meaning it would have, so let's just set it to 1:
https://github.com/zenithdb/zenith/pull/829

I haven't removed protocol message field, it is harmless and probably we'll get back to this.

> According to further research on how walkeeper gets the TLI ... which is uninitialized

Interesting, I haven't realized ThisTimelineID lives uninitialized until first `RecoveryInProgress` call. walproposer side should also be cleaned up.
