### ISSUE TITLE
pageserver - timeline metadata after layer eviction

### ISSUE THREAD

**Issue by patins** [zenithdb/zenith#828]
Currently timeline metadata is only written after checkpoint. It's not even clear how to write metadata after eviction, because `disk_consistent_lsn` cannot be bumped.

cc @hlinnaka

**Comment by hlinnaka** [comment]
Yeah, we cannot advance `disk_consistent_lsn` after evicting a layer, unless it happens to be the oldest layer for the timeline. That's OK. It just means that might do some unnecessary work after a crash, to reconstruct a layer from the WAL that we had already created and flushed to disk before the crash.
