### ISSUE TITLE
IntervalTree failed assertion

### ISSUE THREAD

**Issue by patins** [zenithdb/zenith#835]
test_isolation crashed [here](https://app.circleci.com/pipelines/github/zenithdb/zenith/3075/workflows/bee75273-a3fa-476e-90ba-23ee657c5586/jobs/24733/artifacts)

My guess is that we're removing something not present? Also possible that there could be a bug in the IntervalTree impl, but less likely imo

```
thread 'WAL receiver thread' panicked at 'assertion failed: found_start_point', pageserver/src/layered_repository/interval_tree.rs:186:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:50:5
   3: pageserver::layered_repository::interval_tree::IntervalTree<I>::remove
             at /home/circleci/project/pageserver/src/layered_repository/interval_tree.rs:186:9
   4: pageserver::layered_repository::layer_map::LayerMap::remove_historic
             at /home/circleci/project/pageserver/src/layered_repository/layer_map.rs:154:13
   5: pageserver::layered_repository::LayeredTimeline::evict_layer
             at /home/circleci/project/pageserver/src/layered_repository.rs:1280:13
   6: pageserver::layered_repository::evict_layer_if_needed
             at /home/circleci/project/pageserver/src/layered_repository.rs:1885:9
   7: pageserver::walreceiver::walreceiver_main
             at /home/circleci/project/pageserver/src/walreceiver.rs:300:17
   8: pageserver::walreceiver::thread_main
             at /home/circleci/project/pageserver/src/walreceiver.rs:155:19
   9: pageserver::walreceiver::launch_wal_receiver::{{closure}}
             at /home/circleci/project/pageserver/src/walreceiver.rs:107:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by arssher** [comment]
Got that again at
https://app.circleci.com/pipelines/github/zenithdb/zenith/3190/workflows/c66e269f-fb68-44e6-9140-ac8f5c7de187/jobs/26084/artifacts

**Comment by LizardWizzard** [comment]
Got this error on staging during everyday beenchmark run. 
See https://discord.com/channels/869525774699462656/907918139998752779/907918167786008628

**Comment by patins** [comment]
I think what's happening here is:
- walreceiver calls `evict_layer_if_needed`, `evict_layer` is called, write_lock+LayerMap locks are acquired, the InMemoryLayer is moved from the open map to the historics, the locks are released, we begin writing delta/image layers to disk
- GC starts on the checkpointer thread, acquires layermap lock, decides to GC the temporary historic we added in the first part of `evict_layer`, calls `remove_historic` on it, release the layermap lock
-  walreceiver is done writing the delta/image layers to disk, re-acquires the locks, calls `remove_historic` on the InMemoryLayer it previously put there, assertion failed because it was already removed.

If concurrent checkpointing and GC is safe, then we could make remove_historic not worry about the missing case.
If this is not safe, maybe we need to add another lock

**Comment by patins** [comment]
The fix for this has been merged, please let me know if you see this bug pop up again
