### ISSUE TITLE
Consider alternatives to parse_duration crate

### ISSUE THREAD

**Issue by ericseppanen** [zenithdb/zenith#87]
parse_duration gets flagged by `cargo audit` for to a denial-of-service attack possible via malicious input. The crate is no longer maintained, so there won't be a bugfix release.

It doesn't look like we use that package for anything sensitive (just CLI parsing), but it would be nice to fix this so that `cargo audit` and/or `cargo deny` can pass in CI.

**Comment by kelvich** [comment]
+1 for using smth different
