### ISSUE TITLE
pg_regress reloption test failure

### ISSUE THREAD

**Issue by lubennikovaav** [zenithdb/zenith#88]
One more floating bug in CI.
https://github.com/zenithdb/zenith/runs/2487396618

``` --- /home/runner/work/zenith/zenith/control_plane/../vendor/postgres/src/test/regress/expected/reloptions.out	2021-05-02 18:04:43.124502686 +0000
+++ /home/runner/work/zenith/zenith/integration_tests/.zenith/regress/results/reloptions.out	2021-05-02 18:15:35.707502682 +0000
@@ -131,7 +131,7 @@
 SELECT pg_relation_size('reloptions_test') = 0;
  ?column? 
 ----------
- t
+ f
 (1 row)
 ```

May be the same problem as in #85.

**Comment by arssher** [comment]
see also
https://www.postgresql.org/message-id/flat/CAD21AoCFLA%2BmWMoZpGeQ3-88JxuQz7v%2BFeMMJWgT8v8tu470Rg%40mail.gmail.com#2ff703383e6701e45905b9416296e265

**Comment by lubennikovaav** [comment]
Fixed in upstream https://github.com/postgres/postgres/commit/fe246d1c111d43fd60a1b0afff25ed09b7ae11eb
