### ISSUE TITLE
Trim safekeeper WAL based on s3_lsn feedback from pageserver

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#944]

**Comment by stepashka** [comment]
@SomeoneToIgnore , can you help with this?

**Comment by SomeoneToIgnore** [comment]
I know what to do now, will deal with my current task and add this, before Friday.

**Comment by SomeoneToIgnore** [comment]
https://github.com/zenithdb/zenith/pull/991

**Comment by stepashka** [comment]
note, without #1049 our trimming isn't always correct
