### ISSUE TITLE
Return nice error if GetPage@LSN is called for LSN that has already been garbage collected

### ISSUE THREAD

**Issue by hlinnaka** [zenithdb/zenith#95]
We have commented-out code to maintain a "first valid LSN", but it's never advanced.

We should implement that mechanism in the garbage collection, where if you ask for page at LSN X, but page version X has already been deleted, you get an error. Not sure if  single "first valid LSN" is enough, though. For example, if you wanted to retain a snapshot of the database at one specific point in time from one month ago, and also all the history for the last 24 hours, a single LSN isn't enough to represent that.

_Originally posted by @ericseppanen in https://github.com/zenithdb/zenith/pull/79#discussion_r624869966_

**Comment by kelvich** [comment]
AFAIK that is done when pageserver<->compute protocol was refactored. Feel free to reopen if I'm wrong.

**Comment by hlinnaka** [comment]
> AFAIK that is done when pageserver<->compute protocol was refactored. Feel free to reopen if I'm wrong.

Nope, this issue still remains.

**Comment by LizardWizzard** [comment]
I'm moving relevant part of the discussion from #863.

I've faced related problem when debugging gc issues #863. Problem I found is that we can create a branch based on lsn that was already garbage collected. I think aside from nice error we should prohibit this in the first place. In my case  branching was also involved, so lsn that was garbage collected in parent branch was perfectly valid for the child branch. So even with prettier error it wouldn't have helped me.

I propose to revive concept of first valid lsn or as it is called in #863 latest gc horizon. And add a check that creation of new branches it prohibited for lsn's that are out of scope. This should help to avoid such kind of GetPage@lsn errors.

@hlinnaka @lubennikovaav thoughts?

**Comment by hlinnaka** [comment]
Sounds good.

In the future, there might be additional points-in-time or even ranges for which we have kept the history. For example, if we have a user interface to create a "snapshot" with a name, then we would keep the page versions at that LSN. So a simple "first valid LSN" might not be enough in the future. But it's good enough for now.

**Comment by LizardWizzard** [comment]
Snapshot at some point in time is relatively simple. This is just a branchpoint. 

Ranges are trickier. It sounds like setting gc horizon to this range, but gc horizon is an lsn, which is not a human friendly time representation :)

> Sounds good.

Great! I'll split changes related to this issue from #863 and create a separate PR
