### ISSUE TITLE
Auto-deploy for proxy

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#951]

**Comment by cicdteam** [comment]
@kelvich currently proxy deployed as k8s workload (deployment + service with `type: loadBalancer`). Should I create kubernetes manifests or small helm chart for proxy in this repository and add it to staging-deploy flow in CircleCI ?

**Comment by kelvich** [comment]
Yeah, makes sense. We also decided to move to `start.zenith.tech` instead of `lb.zenith.tech`
