### ISSUE TITLE
Epic: pre-launch performance testing safekeeper and follow ups

### ISSUE THREAD

**Issue by stepashka** [zenithdb/zenith#961]
## Motivation
When we launch, Compute -> Safekeeper performance should be roughly on par with streaming postgres replication.

## DoD
we have rough numbers that compare the performance of Zenith with PG streaming replication
low hanging fruits for improvements are implemented, tasks for bigger issues are created and linked.

## Tasks
- [x] #799
- [x] #780
- [x] unnecessary queue traversals in WAL proposer
- [x] #858 
- [x] #960
- [x] #1141
- [x] #1144 

Follow ups for the future that came up from this:
- #1005

**Comment by petuhovskiy** [comment]
I think we reached DoD, should we close this epic now? @stepashka

**Comment by petuhovskiy** [comment]
#1141 is fixed now
