### ISSUE TITLE
Fix pageserver shutdown issues and time it takes to restart

### ISSUE THREAD

**Issue by kelvich** [zenithdb/zenith#981]
Stas — 12/07/2021
During our deploy systemd service restart takes about a half an hour. I was puzzled initially, but didn't investigate it. Later while playing with WAL inspection tool (one that I used to create strange images about layer update patterns) I've noticed that shutdown time for my rust script was ~= run time ~= 90min. Looking into debugger it seems that all that time was spent in a memory deallocation. Which doest not make a lot of sense when returning from main(). Not sure how much time is spent for fsyncs and how much for a deallocation, but probably quite a lot. Should we call std::mem:forget or smth similar around the exit?

Pat — 12/07/2021
I think we could use std::process::exit, it won't unwind any stacks
I'm a little hesitant though

Stas — 12/07/2021
oh, that would easier than trying to mem::forget all big structures. Any problems assotiatiated with that?

Pat — 12/07/2021
We need to be sure anything that is normally done in destructors is done before calling it (IO/log flushes come to mind -- we'd also have to do this with forget) 
but I think it's a relatively simple implementation (just putting it after our own graceful shutdown code completes)

**Comment by stepashka** [comment]
after this is complete, we probably want to revisit our deployment/restart scripts and go back to graceful shutdowns during the deployments

**Comment by hlinnaka** [comment]
I believe this has been fixed by https://github.com/zenithdb/zenith/pull/1108.
