### ISSUE TITLE
Epic: fix multiple pageserver shutdown issues

### ISSUE THREAD

**Issue by LizardWizzard** [zenithdb/zenith#988]
There are some places which can prevent pageserver from shutting down cleanly in a reasonable time.
One of them is walreceiver. If connection is alive and no messages in there it can block inside recv indefinitely. The problem is that this recv is inside tokio postgres which is inside the sync wrapper we use so we do not have a direct access to to the underlying runtime.

There are some options available for us:
* Use async tokio-posgtres and have a runtime.block_on in our code so we can tokio::select! around the receiving new message and a timeout.
* Use async tokio postgres, tokio::select! around new message and a timeout, and use spawn_blocking to call into layered repo code so it wont block the executor.
* Use async everywhere (this is a big change with it's own pros and cons so this might not be desirable just yet).

similar problem also exists for page_service thread. But here we have more control because this is our own protocol. But essentially the problem is the same. Here we can switch to async sockets using something like [mio](https://github.com/tokio-rs/mio) but in my opinion this is a bit pointless because in this case we are starting to implement our own async runtime :)

Now we use this flag `tenant_mgr::shutdown_requested()` to check for shutdown condition, and if we do not check it somewhere, e. g. in long running loop, this can result in a longer shutdown times. 

This can be treated in a few different ways. We can fix just this particular issue with walreceiver blocking that appears to be the cause of problems with automatic deployment, or change how our shutdown routines work to cover all components in a unified way, as an example we can have a shutdown sequence like that: 
* shutdown signal received
* it is broadcasted to all components that need it
* all needed cleanup is done by these components (checkpointing, sending shutdown message to active connections etc.)
* all components confirm that we can shutdown cleanly
* exit the process
This is inspired by tokio's example app [mini-redis](https://github.com/tokio-rs/mini-redis).

Additional note on shutting down walreceiver. If there is alive compute node and we try to shutdown walreceiver then safekeeper will reconnect to pageserver after a second, so with alive compute there is almost no sense in shutting down walreceiver. Though if we want to forcibly restart pageserver with running compute, this reconnect seems ok to me, because after pageserver restart is completed, connection will be reestablished and replication continues normally

- [x] #981
- [x] #1036
- [ ] #470

**Comment by LizardWizzard** [comment]
Also we should keep in mind that we should be able to shut down just one tenant instead of the whole pageserver

**Comment by hlinnaka** [comment]
This has been fixed by https://github.com/zenithdb/zenith/pull/1108. There's probably more cleanup and improvements we could make - we rely on polling with 5 interval in the page handler threads to notice a shutdown for example - but this is good enough for now.
